import { PrismaClient } from '@prisma/client';
import { getCategories } from './05-categories';

const prisma = new PrismaClient();

export interface SubcategoryData {
  name: string;
  slug: string;
  description: string;
  sortOrder: number;
  categorySlug: string;
}

export const subcategories: SubcategoryData[] = [
  // Electronics subcategories
  {
    name: 'Smartphones',
    slug: 'smartphones',
    description: 'Mobile phones and accessories',
    sortOrder: 1,
    categorySlug: 'electronics',
  },
  {
    name: 'Laptops',
    slug: 'laptops',
    description: 'Laptop computers and accessories',
    sortOrder: 2,
    categorySlug: 'electronics',
  },
  {
    name: 'Tablets',
    slug: 'tablets',
    description: 'Tablet devices and accessories',
    sortOrder: 3,
    categorySlug: 'electronics',
  },
  {
    name: 'Audio & Headphones',
    slug: 'audio-headphones',
    description: 'Audio equipment and headphones',
    sortOrder: 4,
    categorySlug: 'electronics',
  },
  {
    name: 'Cameras',
    slug: 'cameras',
    description: 'Digital cameras and photography equipment',
    sortOrder: 5,
    categorySlug: 'electronics',
  },
  {
    name: 'Gaming',
    slug: 'gaming',
    description: 'Gaming consoles and accessories',
    sortOrder: 6,
    categorySlug: 'electronics',
  },
  {
    name: 'Smart Home',
    slug: 'smart-home',
    description: 'Smart home devices and automation',
    sortOrder: 7,
    categorySlug: 'electronics',
  },
  {
    name: 'Wearables',
    slug: 'wearables',
    description: 'Smart watches and fitness trackers',
    sortOrder: 8,
    categorySlug: 'electronics',
  },
  {
    name: 'Accessories',
    slug: 'electronics-accessories',
    description: 'Electronic accessories and cables',
    sortOrder: 9,
    categorySlug: 'electronics',
  },
  {
    name: 'Components',
    slug: 'components',
    description: 'Computer and electronic components',
    sortOrder: 10,
    categorySlug: 'electronics',
  },

  // Clothing & Fashion subcategories
  {
    name: "Men's Clothing",
    slug: 'mens-clothing',
    description: "Men's apparel and fashion",
    sortOrder: 1,
    categorySlug: 'clothing-fashion',
  },
  {
    name: "Women's Clothing",
    slug: 'womens-clothing',
    description: "Women's apparel and fashion",
    sortOrder: 2,
    categorySlug: 'clothing-fashion',
  },
  {
    name: "Kids' Clothing",
    slug: 'kids-clothing',
    description: "Children's apparel and fashion",
    sortOrder: 3,
    categorySlug: 'clothing-fashion',
  },
  {
    name: 'Shoes',
    slug: 'shoes',
    description: 'Footwear for all ages',
    sortOrder: 4,
    categorySlug: 'clothing-fashion',
  },
  {
    name: 'Accessories',
    slug: 'fashion-accessories',
    description: 'Fashion accessories and jewelry',
    sortOrder: 5,
    categorySlug: 'clothing-fashion',
  },
  {
    name: 'Bags & Purses',
    slug: 'bags-purses',
    description: 'Handbags, purses, and luggage',
    sortOrder: 6,
    categorySlug: 'clothing-fashion',
  },
  {
    name: 'Activewear',
    slug: 'activewear',
    description: 'Sports and athletic clothing',
    sortOrder: 7,
    categorySlug: 'clothing-fashion',
  },
  {
    name: 'Formal Wear',
    slug: 'formal-wear',
    description: 'Formal and business attire',
    sortOrder: 8,
    categorySlug: 'clothing-fashion',
  },
  {
    name: 'Underwear & Lingerie',
    slug: 'underwear-lingerie',
    description: 'Intimate apparel and undergarments',
    sortOrder: 9,
    categorySlug: 'clothing-fashion',
  },
  {
    name: 'Seasonal',
    slug: 'seasonal-clothing',
    description: 'Seasonal and weather-specific clothing',
    sortOrder: 10,
    categorySlug: 'clothing-fashion',
  },

  // Home & Garden subcategories
  {
    name: 'Furniture',
    slug: 'furniture',
    description: 'Home and office furniture',
    sortOrder: 1,
    categorySlug: 'home-garden',
  },
  {
    name: 'Kitchen & Dining',
    slug: 'kitchen-dining',
    description: 'Kitchen appliances and dining items',
    sortOrder: 2,
    categorySlug: 'home-garden',
  },
  {
    name: 'Bedding & Bath',
    slug: 'bedding-bath',
    description: 'Bedding, bath, and linens',
    sortOrder: 3,
    categorySlug: 'home-garden',
  },
  {
    name: 'Home Decor',
    slug: 'home-decor',
    description: 'Decorative items and home accessories',
    sortOrder: 4,
    categorySlug: 'home-garden',
  },
  {
    name: 'Lighting',
    slug: 'lighting',
    description: 'Lighting fixtures and lamps',
    sortOrder: 5,
    categorySlug: 'home-garden',
  },
  {
    name: 'Storage & Organization',
    slug: 'storage-organization',
    description: 'Storage solutions and organization',
    sortOrder: 6,
    categorySlug: 'home-garden',
  },
  {
    name: 'Tools & Hardware',
    slug: 'tools-hardware',
    description: 'Tools and hardware supplies',
    sortOrder: 7,
    categorySlug: 'home-garden',
  },
  {
    name: 'Appliances',
    slug: 'appliances',
    description: 'Home appliances and electronics',
    sortOrder: 8,
    categorySlug: 'home-garden',
  },
  {
    name: 'Cleaning Supplies',
    slug: 'cleaning-supplies',
    description: 'Cleaning products and supplies',
    sortOrder: 9,
    categorySlug: 'home-garden',
  },
  {
    name: 'Safety & Security',
    slug: 'safety-security',
    description: 'Home safety and security products',
    sortOrder: 10,
    categorySlug: 'home-garden',
  },

  // Sports & Outdoors subcategories
  {
    name: 'Fitness Equipment',
    slug: 'fitness-equipment',
    description: 'Exercise and fitness equipment',
    sortOrder: 1,
    categorySlug: 'sports-outdoors',
  },
  {
    name: 'Outdoor Gear',
    slug: 'outdoor-gear',
    description: 'Camping and outdoor equipment',
    sortOrder: 2,
    categorySlug: 'sports-outdoors',
  },
  {
    name: 'Team Sports',
    slug: 'team-sports',
    description: 'Team sports equipment and gear',
    sortOrder: 3,
    categorySlug: 'sports-outdoors',
  },
  {
    name: 'Water Sports',
    slug: 'water-sports',
    description: 'Swimming and water sports equipment',
    sortOrder: 4,
    categorySlug: 'sports-outdoors',
  },
  {
    name: 'Winter Sports',
    slug: 'winter-sports',
    description: 'Skiing, snowboarding, and winter gear',
    sortOrder: 5,
    categorySlug: 'sports-outdoors',
  },
  {
    name: 'Cycling',
    slug: 'cycling',
    description: 'Bicycles and cycling accessories',
    sortOrder: 6,
    categorySlug: 'sports-outdoors',
  },
  {
    name: 'Running',
    slug: 'running',
    description: 'Running shoes and accessories',
    sortOrder: 7,
    categorySlug: 'sports-outdoors',
  },
  {
    name: 'Golf',
    slug: 'golf',
    description: 'Golf equipment and accessories',
    sortOrder: 8,
    categorySlug: 'sports-outdoors',
  },
  {
    name: 'Hunting & Fishing',
    slug: 'hunting-fishing',
    description: 'Hunting and fishing equipment',
    sortOrder: 9,
    categorySlug: 'sports-outdoors',
  },
  {
    name: 'Sports Apparel',
    slug: 'sports-apparel',
    description: 'Sports clothing and uniforms',
    sortOrder: 10,
    categorySlug: 'sports-outdoors',
  },

  // Books & Media subcategories
  {
    name: 'Fiction',
    slug: 'fiction',
    description: 'Fiction books and novels',
    sortOrder: 1,
    categorySlug: 'books-media',
  },
  {
    name: 'Non-Fiction',
    slug: 'non-fiction',
    description: 'Non-fiction books and reference',
    sortOrder: 2,
    categorySlug: 'books-media',
  },
  {
    name: "Children's Books",
    slug: 'childrens-books',
    description: 'Books for children and young adults',
    sortOrder: 3,
    categorySlug: 'books-media',
  },
  {
    name: 'Educational',
    slug: 'educational',
    description: 'Educational books and textbooks',
    sortOrder: 4,
    categorySlug: 'books-media',
  },
  {
    name: 'Movies & TV',
    slug: 'movies-tv',
    description: 'DVDs, Blu-rays, and streaming media',
    sortOrder: 5,
    categorySlug: 'books-media',
  },
  {
    name: 'Music',
    slug: 'music',
    description: 'CDs, vinyl records, and digital music',
    sortOrder: 6,
    categorySlug: 'books-media',
  },
  {
    name: 'Magazines',
    slug: 'magazines',
    description: 'Magazines and periodicals',
    sortOrder: 7,
    categorySlug: 'books-media',
  },
  {
    name: 'Comics & Graphic Novels',
    slug: 'comics-graphic-novels',
    description: 'Comic books and graphic novels',
    sortOrder: 8,
    categorySlug: 'books-media',
  },
  {
    name: 'Audiobooks',
    slug: 'audiobooks',
    description: 'Audio books and spoken word',
    sortOrder: 9,
    categorySlug: 'books-media',
  },
  {
    name: 'Digital Media',
    slug: 'digital-media',
    description: 'E-books and digital downloads',
    sortOrder: 10,
    categorySlug: 'books-media',
  },

  // Health & Beauty subcategories
  {
    name: 'Skincare',
    slug: 'skincare',
    description: 'Facial and body skincare products',
    sortOrder: 1,
    categorySlug: 'health-beauty',
  },
  {
    name: 'Makeup',
    slug: 'makeup',
    description: 'Cosmetics and makeup products',
    sortOrder: 2,
    categorySlug: 'health-beauty',
  },
  {
    name: 'Hair Care',
    slug: 'hair-care',
    description: 'Hair care products and treatments',
    sortOrder: 3,
    categorySlug: 'health-beauty',
  },
  {
    name: 'Fragrances',
    slug: 'fragrances',
    description: 'Perfumes and colognes',
    sortOrder: 4,
    categorySlug: 'health-beauty',
  },
  {
    name: 'Personal Care',
    slug: 'personal-care',
    description: 'Personal hygiene and care products',
    sortOrder: 5,
    categorySlug: 'health-beauty',
  },
  {
    name: 'Health Supplements',
    slug: 'health-supplements',
    description: 'Vitamins and health supplements',
    sortOrder: 6,
    categorySlug: 'health-beauty',
  },
  {
    name: 'Medical Supplies',
    slug: 'medical-supplies',
    description: 'Medical and first aid supplies',
    sortOrder: 7,
    categorySlug: 'health-beauty',
  },
  {
    name: 'Fitness & Wellness',
    slug: 'fitness-wellness',
    description: 'Fitness and wellness products',
    sortOrder: 8,
    categorySlug: 'health-beauty',
  },
  {
    name: "Men's Grooming",
    slug: 'mens-grooming',
    description: "Men's grooming and care products",
    sortOrder: 9,
    categorySlug: 'health-beauty',
  },
  {
    name: 'Natural & Organic',
    slug: 'natural-organic',
    description: 'Natural and organic beauty products',
    sortOrder: 10,
    categorySlug: 'health-beauty',
  },

  // Automotive subcategories
  {
    name: 'Car Parts',
    slug: 'car-parts',
    description: 'Automotive parts and components',
    sortOrder: 1,
    categorySlug: 'automotive',
  },
  {
    name: 'Car Accessories',
    slug: 'car-accessories',
    description: 'Car accessories and modifications',
    sortOrder: 2,
    categorySlug: 'automotive',
  },
  {
    name: 'Tools & Equipment',
    slug: 'automotive-tools',
    description: 'Automotive tools and equipment',
    sortOrder: 3,
    categorySlug: 'automotive',
  },
  {
    name: 'Oils & Fluids',
    slug: 'oils-fluids',
    description: 'Motor oils and automotive fluids',
    sortOrder: 4,
    categorySlug: 'automotive',
  },
  {
    name: 'Tires & Wheels',
    slug: 'tires-wheels',
    description: 'Tires, wheels, and related accessories',
    sortOrder: 5,
    categorySlug: 'automotive',
  },
  {
    name: 'Interior',
    slug: 'automotive-interior',
    description: 'Car interior accessories and parts',
    sortOrder: 6,
    categorySlug: 'automotive',
  },
  {
    name: 'Exterior',
    slug: 'automotive-exterior',
    description: 'Car exterior accessories and parts',
    sortOrder: 7,
    categorySlug: 'automotive',
  },
  {
    name: 'Electronics',
    slug: 'automotive-electronics',
    description: 'Car electronics and audio systems',
    sortOrder: 8,
    categorySlug: 'automotive',
  },
  {
    name: 'Maintenance',
    slug: 'automotive-maintenance',
    description: 'Car maintenance and care products',
    sortOrder: 9,
    categorySlug: 'automotive',
  },
  {
    name: 'Motorcycle',
    slug: 'motorcycle',
    description: 'Motorcycle parts and accessories',
    sortOrder: 10,
    categorySlug: 'automotive',
  },

  // Toys & Games subcategories
  {
    name: 'Action Figures',
    slug: 'action-figures',
    description: 'Action figures and collectible toys',
    sortOrder: 1,
    categorySlug: 'toys-games',
  },
  {
    name: 'Board Games',
    slug: 'board-games',
    description: 'Board games and tabletop games',
    sortOrder: 2,
    categorySlug: 'toys-games',
  },
  {
    name: 'Puzzles',
    slug: 'puzzles',
    description: 'Jigsaw puzzles and brain teasers',
    sortOrder: 3,
    categorySlug: 'toys-games',
  },
  {
    name: 'Educational Toys',
    slug: 'educational-toys',
    description: 'Learning and educational toys',
    sortOrder: 4,
    categorySlug: 'toys-games',
  },
  {
    name: 'Electronic Toys',
    slug: 'electronic-toys',
    description: 'Electronic and interactive toys',
    sortOrder: 5,
    categorySlug: 'toys-games',
  },
  {
    name: 'Outdoor Toys',
    slug: 'outdoor-toys',
    description: 'Outdoor play equipment and toys',
    sortOrder: 6,
    categorySlug: 'toys-games',
  },
  {
    name: 'Arts & Crafts',
    slug: 'toys-arts-crafts',
    description: 'Art supplies and craft kits for kids',
    sortOrder: 7,
    categorySlug: 'toys-games',
  },
  {
    name: 'Dolls & Stuffed Animals',
    slug: 'dolls-stuffed-animals',
    description: 'Dolls, stuffed animals, and plush toys',
    sortOrder: 8,
    categorySlug: 'toys-games',
  },
  {
    name: 'Building Sets',
    slug: 'building-sets',
    description: 'Building blocks and construction sets',
    sortOrder: 9,
    categorySlug: 'toys-games',
  },
  {
    name: 'Video Games',
    slug: 'video-games',
    description: 'Video games and gaming accessories',
    sortOrder: 10,
    categorySlug: 'toys-games',
  },

  // Food & Beverages subcategories
  {
    name: 'Fresh Produce',
    slug: 'fresh-produce',
    description: 'Fresh fruits and vegetables',
    sortOrder: 1,
    categorySlug: 'food-beverages',
  },
  {
    name: 'Meat & Seafood',
    slug: 'meat-seafood',
    description: 'Fresh and frozen meat and seafood',
    sortOrder: 2,
    categorySlug: 'food-beverages',
  },
  {
    name: 'Dairy & Eggs',
    slug: 'dairy-eggs',
    description: 'Dairy products and eggs',
    sortOrder: 3,
    categorySlug: 'food-beverages',
  },
  {
    name: 'Pantry Staples',
    slug: 'pantry-staples',
    description: 'Canned goods and pantry essentials',
    sortOrder: 4,
    categorySlug: 'food-beverages',
  },
  {
    name: 'Beverages',
    slug: 'beverages',
    description: 'Drinks and beverages',
    sortOrder: 5,
    categorySlug: 'food-beverages',
  },
  {
    name: 'Snacks',
    slug: 'snacks',
    description: 'Snacks and convenience foods',
    sortOrder: 6,
    categorySlug: 'food-beverages',
  },
  {
    name: 'Frozen Foods',
    slug: 'frozen-foods',
    description: 'Frozen meals and ingredients',
    sortOrder: 7,
    categorySlug: 'food-beverages',
  },
  {
    name: 'Bakery',
    slug: 'bakery',
    description: 'Bread, pastries, and baked goods',
    sortOrder: 8,
    categorySlug: 'food-beverages',
  },
  {
    name: 'International',
    slug: 'international-food',
    description: 'International and ethnic foods',
    sortOrder: 9,
    categorySlug: 'food-beverages',
  },
  {
    name: 'Organic & Natural',
    slug: 'organic-natural-food',
    description: 'Organic and natural food products',
    sortOrder: 10,
    categorySlug: 'food-beverages',
  },

  // Jewelry & Watches subcategories
  {
    name: 'Rings',
    slug: 'rings',
    description: 'Finger rings and wedding bands',
    sortOrder: 1,
    categorySlug: 'jewelry-watches',
  },
  {
    name: 'Necklaces',
    slug: 'necklaces',
    description: 'Necklaces and pendants',
    sortOrder: 2,
    categorySlug: 'jewelry-watches',
  },
  {
    name: 'Earrings',
    slug: 'earrings',
    description: 'Earrings and ear jewelry',
    sortOrder: 3,
    categorySlug: 'jewelry-watches',
  },
  {
    name: 'Bracelets',
    slug: 'bracelets',
    description: 'Bracelets and bangles',
    sortOrder: 4,
    categorySlug: 'jewelry-watches',
  },
  {
    name: 'Watches',
    slug: 'watches',
    description: 'Wristwatches and timepieces',
    sortOrder: 5,
    categorySlug: 'jewelry-watches',
  },
  {
    name: 'Brooches & Pins',
    slug: 'brooches-pins',
    description: 'Brooches, pins, and lapel accessories',
    sortOrder: 6,
    categorySlug: 'jewelry-watches',
  },
  {
    name: 'Anklets',
    slug: 'anklets',
    description: 'Ankle bracelets and foot jewelry',
    sortOrder: 7,
    categorySlug: 'jewelry-watches',
  },
  {
    name: 'Body Jewelry',
    slug: 'body-jewelry',
    description: 'Body piercing jewelry and accessories',
    sortOrder: 8,
    categorySlug: 'jewelry-watches',
  },
  {
    name: 'Jewelry Sets',
    slug: 'jewelry-sets',
    description: 'Matching jewelry sets and collections',
    sortOrder: 9,
    categorySlug: 'jewelry-watches',
  },
  {
    name: 'Jewelry Care',
    slug: 'jewelry-care',
    description: 'Jewelry cleaning and storage supplies',
    sortOrder: 10,
    categorySlug: 'jewelry-watches',
  },

  // Office Supplies subcategories
  {
    name: 'Writing Instruments',
    slug: 'writing-instruments',
    description: 'Pens, pencils, and writing tools',
    sortOrder: 1,
    categorySlug: 'office-supplies',
  },
  {
    name: 'Paper & Notebooks',
    slug: 'paper-notebooks',
    description: 'Paper products and notebooks',
    sortOrder: 2,
    categorySlug: 'office-supplies',
  },
  {
    name: 'Filing & Organization',
    slug: 'filing-organization',
    description: 'Filing systems and organization tools',
    sortOrder: 3,
    categorySlug: 'office-supplies',
  },
  {
    name: 'Desk Accessories',
    slug: 'desk-accessories',
    description: 'Desk organizers and accessories',
    sortOrder: 4,
    categorySlug: 'office-supplies',
  },
  {
    name: 'Technology',
    slug: 'office-technology',
    description: 'Office technology and electronics',
    sortOrder: 5,
    categorySlug: 'office-supplies',
  },
  {
    name: 'Presentation',
    slug: 'presentation',
    description: 'Presentation boards and supplies',
    sortOrder: 6,
    categorySlug: 'office-supplies',
  },
  {
    name: 'Shipping & Mailing',
    slug: 'shipping-mailing',
    description: 'Shipping supplies and mailing materials',
    sortOrder: 7,
    categorySlug: 'office-supplies',
  },
  {
    name: 'Break Room',
    slug: 'break-room',
    description: 'Break room supplies and amenities',
    sortOrder: 8,
    categorySlug: 'office-supplies',
  },
  {
    name: 'Safety & Security',
    slug: 'office-safety-security',
    description: 'Office safety and security supplies',
    sortOrder: 9,
    categorySlug: 'office-supplies',
  },
  {
    name: 'Cleaning Supplies',
    slug: 'office-cleaning',
    description: 'Office cleaning supplies and equipment',
    sortOrder: 10,
    categorySlug: 'office-supplies',
  },

  // Pet Supplies subcategories
  {
    name: 'Dog Supplies',
    slug: 'dog-supplies',
    description: 'Dog food, toys, and accessories',
    sortOrder: 1,
    categorySlug: 'pet-supplies',
  },
  {
    name: 'Cat Supplies',
    slug: 'cat-supplies',
    description: 'Cat food, toys, and accessories',
    sortOrder: 2,
    categorySlug: 'pet-supplies',
  },
  {
    name: 'Fish & Aquarium',
    slug: 'fish-aquarium',
    description: 'Fish supplies and aquarium equipment',
    sortOrder: 3,
    categorySlug: 'pet-supplies',
  },
  {
    name: 'Bird Supplies',
    slug: 'bird-supplies',
    description: 'Bird food, cages, and accessories',
    sortOrder: 4,
    categorySlug: 'pet-supplies',
  },
  {
    name: 'Small Pets',
    slug: 'small-pets',
    description: 'Supplies for rabbits, hamsters, and small animals',
    sortOrder: 5,
    categorySlug: 'pet-supplies',
  },
  {
    name: 'Reptile Supplies',
    slug: 'reptile-supplies',
    description: 'Reptile food, habitats, and accessories',
    sortOrder: 6,
    categorySlug: 'pet-supplies',
  },
  {
    name: 'Pet Health',
    slug: 'pet-health',
    description: 'Pet health and grooming supplies',
    sortOrder: 7,
    categorySlug: 'pet-supplies',
  },
  {
    name: 'Pet Training',
    slug: 'pet-training',
    description: 'Pet training tools and supplies',
    sortOrder: 8,
    categorySlug: 'pet-supplies',
  },
  {
    name: 'Pet Travel',
    slug: 'pet-travel',
    description: 'Pet carriers and travel accessories',
    sortOrder: 9,
    categorySlug: 'pet-supplies',
  },
  {
    name: 'Pet Furniture',
    slug: 'pet-furniture',
    description: 'Pet beds, houses, and furniture',
    sortOrder: 10,
    categorySlug: 'pet-supplies',
  },

  // Baby & Kids subcategories
  {
    name: 'Baby Clothing',
    slug: 'baby-clothing',
    description: 'Infant and toddler clothing',
    sortOrder: 1,
    categorySlug: 'baby-kids',
  },
  {
    name: 'Diapering',
    slug: 'diapering',
    description: 'Diapers and diapering supplies',
    sortOrder: 2,
    categorySlug: 'baby-kids',
  },
  {
    name: 'Feeding',
    slug: 'baby-feeding',
    description: 'Baby bottles, formula, and feeding supplies',
    sortOrder: 3,
    categorySlug: 'baby-kids',
  },
  {
    name: 'Nursery',
    slug: 'nursery',
    description: 'Nursery furniture and decor',
    sortOrder: 4,
    categorySlug: 'baby-kids',
  },
  {
    name: 'Safety',
    slug: 'baby-safety',
    description: 'Baby safety equipment and monitors',
    sortOrder: 5,
    categorySlug: 'baby-kids',
  },
  {
    name: 'Toys & Play',
    slug: 'baby-toys-play',
    description: 'Baby toys and play equipment',
    sortOrder: 6,
    categorySlug: 'baby-kids',
  },
  {
    name: 'Bath & Grooming',
    slug: 'baby-bath-grooming',
    description: 'Baby bath and grooming supplies',
    sortOrder: 7,
    categorySlug: 'baby-kids',
  },
  {
    name: 'Travel',
    slug: 'baby-travel',
    description: 'Baby strollers, car seats, and travel gear',
    sortOrder: 8,
    categorySlug: 'baby-kids',
  },
  {
    name: 'Health',
    slug: 'baby-health',
    description: 'Baby health and medical supplies',
    sortOrder: 9,
    categorySlug: 'baby-kids',
  },
  {
    name: 'Gear & Equipment',
    slug: 'baby-gear-equipment',
    description: 'Baby gear and equipment',
    sortOrder: 10,
    categorySlug: 'baby-kids',
  },

  // Travel & Luggage subcategories
  {
    name: 'Luggage',
    slug: 'luggage',
    description: 'Suitcases and travel bags',
    sortOrder: 1,
    categorySlug: 'travel-luggage',
  },
  {
    name: 'Backpacks',
    slug: 'travel-backpacks',
    description: 'Travel backpacks and daypacks',
    sortOrder: 2,
    categorySlug: 'travel-luggage',
  },
  {
    name: 'Travel Accessories',
    slug: 'travel-accessories',
    description: 'Travel accessories and organizers',
    sortOrder: 3,
    categorySlug: 'travel-luggage',
  },
  {
    name: 'Electronics',
    slug: 'travel-electronics',
    description: 'Travel electronics and adapters',
    sortOrder: 4,
    categorySlug: 'travel-luggage',
  },
  {
    name: 'Comfort',
    slug: 'travel-comfort',
    description: 'Travel comfort and wellness items',
    sortOrder: 5,
    categorySlug: 'travel-luggage',
  },
  {
    name: 'Security',
    slug: 'travel-security',
    description: 'Travel security and safety items',
    sortOrder: 6,
    categorySlug: 'travel-luggage',
  },
  {
    name: 'Outdoor Travel',
    slug: 'outdoor-travel',
    description: 'Camping and outdoor travel gear',
    sortOrder: 7,
    categorySlug: 'travel-luggage',
  },
  {
    name: 'Business Travel',
    slug: 'business-travel',
    description: 'Business travel accessories',
    sortOrder: 8,
    categorySlug: 'travel-luggage',
  },
  {
    name: 'Travel Documents',
    slug: 'travel-documents',
    description: 'Travel document holders and organizers',
    sortOrder: 9,
    categorySlug: 'travel-luggage',
  },
  {
    name: 'Gift & Souvenirs',
    slug: 'travel-gift-souvenirs',
    description: 'Travel gifts and souvenir items',
    sortOrder: 10,
    categorySlug: 'travel-luggage',
  },

  // Musical Instruments subcategories
  {
    name: 'Guitars',
    slug: 'guitars',
    description: 'Acoustic and electric guitars',
    sortOrder: 1,
    categorySlug: 'musical-instruments',
  },
  {
    name: 'Pianos & Keyboards',
    slug: 'pianos-keyboards',
    description: 'Pianos, keyboards, and synthesizers',
    sortOrder: 2,
    categorySlug: 'musical-instruments',
  },
  {
    name: 'Drums & Percussion',
    slug: 'drums-percussion',
    description: 'Drum sets and percussion instruments',
    sortOrder: 3,
    categorySlug: 'musical-instruments',
  },
  {
    name: 'Brass Instruments',
    slug: 'brass-instruments',
    description: 'Trumpets, trombones, and brass instruments',
    sortOrder: 4,
    categorySlug: 'musical-instruments',
  },
  {
    name: 'Woodwind Instruments',
    slug: 'woodwind-instruments',
    description: 'Flutes, clarinets, and woodwind instruments',
    sortOrder: 5,
    categorySlug: 'musical-instruments',
  },
  {
    name: 'String Instruments',
    slug: 'string-instruments',
    description: 'Violins, cellos, and string instruments',
    sortOrder: 6,
    categorySlug: 'musical-instruments',
  },
  {
    name: 'Accessories',
    slug: 'music-accessories',
    description: 'Musical instrument accessories and parts',
    sortOrder: 7,
    categorySlug: 'musical-instruments',
  },
  {
    name: 'Audio Equipment',
    slug: 'audio-equipment',
    description: 'Amplifiers, speakers, and audio equipment',
    sortOrder: 8,
    categorySlug: 'musical-instruments',
  },
  {
    name: 'Recording',
    slug: 'recording-equipment',
    description: 'Recording equipment and software',
    sortOrder: 9,
    categorySlug: 'musical-instruments',
  },
  {
    name: 'Sheet Music',
    slug: 'sheet-music',
    description: 'Sheet music and music books',
    sortOrder: 10,
    categorySlug: 'musical-instruments',
  },

  // Art & Crafts subcategories
  {
    name: 'Drawing',
    slug: 'drawing',
    description: 'Drawing supplies and materials',
    sortOrder: 1,
    categorySlug: 'art-crafts',
  },
  {
    name: 'Painting',
    slug: 'painting',
    description: 'Paints, brushes, and painting supplies',
    sortOrder: 2,
    categorySlug: 'art-crafts',
  },
  {
    name: 'Sculpting',
    slug: 'sculpting',
    description: 'Clay, modeling materials, and sculpting tools',
    sortOrder: 3,
    categorySlug: 'art-crafts',
  },
  {
    name: 'Paper Crafts',
    slug: 'paper-crafts',
    description: 'Paper, cardstock, and paper crafting supplies',
    sortOrder: 4,
    categorySlug: 'art-crafts',
  },
  {
    name: 'Fabric & Textiles',
    slug: 'fabric-textiles',
    description: 'Fabric, yarn, and textile supplies',
    sortOrder: 5,
    categorySlug: 'art-crafts',
  },
  {
    name: 'Jewelry Making',
    slug: 'jewelry-making',
    description: 'Jewelry making supplies and tools',
    sortOrder: 6,
    categorySlug: 'art-crafts',
  },
  {
    name: 'Woodworking',
    slug: 'woodworking',
    description: 'Woodworking tools and materials',
    sortOrder: 7,
    categorySlug: 'art-crafts',
  },
  {
    name: 'Scrapbooking',
    slug: 'scrapbooking',
    description: 'Scrapbooking supplies and materials',
    sortOrder: 8,
    categorySlug: 'art-crafts',
  },
  {
    name: 'Candle Making',
    slug: 'candle-making',
    description: 'Candle making supplies and materials',
    sortOrder: 9,
    categorySlug: 'art-crafts',
  },
  {
    name: 'Tools & Equipment',
    slug: 'craft-tools-equipment',
    description: 'Crafting tools and equipment',
    sortOrder: 10,
    categorySlug: 'art-crafts',
  },

  // Industrial & Scientific subcategories
  {
    name: 'Lab Equipment',
    slug: 'lab-equipment',
    description: 'Laboratory equipment and instruments',
    sortOrder: 1,
    categorySlug: 'industrial-scientific',
  },
  {
    name: 'Measuring Tools',
    slug: 'measuring-tools',
    description: 'Precision measuring tools and instruments',
    sortOrder: 2,
    categorySlug: 'industrial-scientific',
  },
  {
    name: 'Safety Equipment',
    slug: 'safety-equipment',
    description: 'Industrial safety equipment and PPE',
    sortOrder: 3,
    categorySlug: 'industrial-scientific',
  },
  {
    name: 'Power Tools',
    slug: 'power-tools',
    description: 'Industrial power tools and equipment',
    sortOrder: 4,
    categorySlug: 'industrial-scientific',
  },
  {
    name: 'Fasteners',
    slug: 'fasteners',
    description: 'Bolts, screws, and fastening hardware',
    sortOrder: 5,
    categorySlug: 'industrial-scientific',
  },
  {
    name: 'Electrical',
    slug: 'electrical-supplies',
    description: 'Electrical supplies and components',
    sortOrder: 6,
    categorySlug: 'industrial-scientific',
  },
  {
    name: 'Plumbing',
    slug: 'plumbing-supplies',
    description: 'Plumbing supplies and fittings',
    sortOrder: 7,
    categorySlug: 'industrial-scientific',
  },
  {
    name: 'HVAC',
    slug: 'hvac',
    description: 'Heating, ventilation, and air conditioning supplies',
    sortOrder: 8,
    categorySlug: 'industrial-scientific',
  },
  {
    name: 'Materials',
    slug: 'industrial-materials',
    description: 'Industrial materials and supplies',
    sortOrder: 9,
    categorySlug: 'industrial-scientific',
  },
  {
    name: 'Testing Equipment',
    slug: 'testing-equipment',
    description: 'Testing and inspection equipment',
    sortOrder: 10,
    categorySlug: 'industrial-scientific',
  },

  // Garden & Outdoor subcategories
  {
    name: 'Garden Tools',
    slug: 'garden-tools',
    description: 'Gardening tools and equipment',
    sortOrder: 1,
    categorySlug: 'garden-outdoor',
  },
  {
    name: 'Plants & Seeds',
    slug: 'plants-seeds',
    description: 'Plants, seeds, and gardening supplies',
    sortOrder: 2,
    categorySlug: 'garden-outdoor',
  },
  {
    name: 'Outdoor Furniture',
    slug: 'outdoor-furniture',
    description: 'Patio furniture and outdoor seating',
    sortOrder: 3,
    categorySlug: 'garden-outdoor',
  },
  {
    name: 'Grills & BBQ',
    slug: 'grills-bbq',
    description: 'Grills, barbecues, and outdoor cooking',
    sortOrder: 4,
    categorySlug: 'garden-outdoor',
  },
  {
    name: 'Outdoor Lighting',
    slug: 'outdoor-lighting',
    description: 'Outdoor lighting and landscape lighting',
    sortOrder: 5,
    categorySlug: 'garden-outdoor',
  },
  {
    name: 'Water Features',
    slug: 'water-features',
    description: 'Fountains, ponds, and water features',
    sortOrder: 6,
    categorySlug: 'garden-outdoor',
  },
  {
    name: 'Pest Control',
    slug: 'pest-control',
    description: 'Garden pest control and fertilizers',
    sortOrder: 7,
    categorySlug: 'garden-outdoor',
  },
  {
    name: 'Storage',
    slug: 'outdoor-storage',
    description: 'Outdoor storage sheds and containers',
    sortOrder: 8,
    categorySlug: 'garden-outdoor',
  },
  {
    name: 'Decorative',
    slug: 'garden-decorative',
    description: 'Garden decorations and ornaments',
    sortOrder: 9,
    categorySlug: 'garden-outdoor',
  },
  {
    name: 'Seasonal',
    slug: 'garden-seasonal',
    description: 'Seasonal garden supplies and decorations',
    sortOrder: 10,
    categorySlug: 'garden-outdoor',
  },

  // Collectibles subcategories
  {
    name: 'Antiques',
    slug: 'antiques',
    description: 'Antique items and collectibles',
    sortOrder: 1,
    categorySlug: 'collectibles',
  },
  {
    name: 'Coins & Currency',
    slug: 'coins-currency',
    description: 'Coins, currency, and numismatics',
    sortOrder: 2,
    categorySlug: 'collectibles',
  },
  {
    name: 'Stamps',
    slug: 'stamps',
    description: 'Postage stamps and philately',
    sortOrder: 3,
    categorySlug: 'collectibles',
  },
  {
    name: 'Sports Memorabilia',
    slug: 'sports-memorabilia',
    description: 'Sports cards and memorabilia',
    sortOrder: 4,
    categorySlug: 'collectibles',
  },
  {
    name: 'Trading Cards',
    slug: 'trading-cards',
    description: 'Trading cards and collectible card games',
    sortOrder: 5,
    categorySlug: 'collectibles',
  },
  {
    name: 'Action Figures',
    slug: 'collectible-action-figures',
    description: 'Collectible action figures and toys',
    sortOrder: 6,
    categorySlug: 'collectibles',
  },
  {
    name: 'Art & Prints',
    slug: 'art-prints',
    description: 'Art prints and collectible artwork',
    sortOrder: 7,
    categorySlug: 'collectibles',
  },
  {
    name: 'Vintage Items',
    slug: 'vintage-items',
    description: 'Vintage and retro collectibles',
    sortOrder: 8,
    categorySlug: 'collectibles',
  },
  {
    name: 'Limited Editions',
    slug: 'limited-editions',
    description: 'Limited edition collectibles',
    sortOrder: 9,
    categorySlug: 'collectibles',
  },
  {
    name: 'Display & Storage',
    slug: 'display-storage',
    description: 'Display cases and storage for collectibles',
    sortOrder: 10,
    categorySlug: 'collectibles',
  },

  // Digital Services subcategories
  {
    name: 'Software',
    slug: 'software',
    description: 'Software applications and programs',
    sortOrder: 1,
    categorySlug: 'digital-services',
  },
  {
    name: 'Digital Media',
    slug: 'digital-media',
    description: 'Digital downloads and media files',
    sortOrder: 2,
    categorySlug: 'digital-services',
  },
  {
    name: 'Online Courses',
    slug: 'online-courses',
    description: 'Educational courses and training',
    sortOrder: 3,
    categorySlug: 'digital-services',
  },
  {
    name: 'Web Services',
    slug: 'web-services',
    description: 'Web hosting and online services',
    sortOrder: 4,
    categorySlug: 'digital-services',
  },
  {
    name: 'Mobile Apps',
    slug: 'mobile-apps',
    description: 'Mobile applications and app services',
    sortOrder: 5,
    categorySlug: 'digital-services',
  },
  {
    name: 'Cloud Services',
    slug: 'cloud-services',
    description: 'Cloud storage and computing services',
    sortOrder: 6,
    categorySlug: 'digital-services',
  },
  {
    name: 'Digital Marketing',
    slug: 'digital-marketing',
    description: 'Digital marketing and advertising services',
    sortOrder: 7,
    categorySlug: 'digital-services',
  },
  {
    name: 'Design Services',
    slug: 'design-services',
    description: 'Graphic design and creative services',
    sortOrder: 8,
    categorySlug: 'digital-services',
  },
  {
    name: 'Consulting',
    slug: 'digital-consulting',
    description: 'Digital consulting and advisory services',
    sortOrder: 9,
    categorySlug: 'digital-services',
  },
  {
    name: 'Support Services',
    slug: 'support-services',
    description: 'Technical support and maintenance services',
    sortOrder: 10,
    categorySlug: 'digital-services',
  },
];

export async function seedSubcategories(): Promise<void> {
  console.log('📁 Seeding subcategories...');

  const categories = await getCategories();
  const categoryMap = new Map(categories.map((cat) => [cat.slug, cat.id]));

  let seededCount = 0;

  for (const subcategory of subcategories) {
    const categoryId = categoryMap.get(subcategory.categorySlug);

    if (!categoryId) {
      console.warn(
        `⚠️  Category not found for subcategory: ${subcategory.name}`
      );
      continue;
    }

    await prisma.subcategory.upsert({
      where: { slug: subcategory.slug },
      update: {
        name: subcategory.name,
        slug: subcategory.slug,
        description: subcategory.description,
        sortOrder: subcategory.sortOrder,
        categoryId,
      },
      create: {
        name: subcategory.name,
        slug: subcategory.slug,
        description: subcategory.description,
        sortOrder: subcategory.sortOrder,
        categoryId,
      },
    });

    seededCount++;
  }

  console.log(`✅ Seeded ${seededCount} subcategories`);
}

export async function getSubcategories() {
  return await prisma.subcategory.findMany({
    include: {
      category: true,
    },
  });
}
