import { PrismaClient } from '@prisma/client';
import { getSubcategories } from './06-subcategories';

const prisma = new PrismaClient();

export interface ProductData {
  name: string;
  description: string;
  sku: string;
  isFeatured: boolean;
  sortOrder: number;
  subcategorySlug: string;
  prices: {
    price: number;
    salePrice?: number;
    currency: string;
  }[];
  stock: {
    quantity: number;
    reserved: number;
    minThreshold: number;
    maxThreshold?: number;
  };
}

// Realistic product names for each subcategory
const productNames: Record<string, string[]> = {
  // Electronics
  smartphones: [
    'iPhone 15 Pro Max',
    'Samsung Galaxy S24 Ultra',
    'Google Pixel 8 Pro',
    'OnePlus 12',
    'Xiaomi 14 Pro',
    'iPhone 15',
    'Samsung Galaxy S24',
    'Google Pixel 8',
    'OnePlus 12R',
    'Xiaomi 14',
  ],
  laptops: [
    'MacBook Pro 16-inch M3',
    'Dell XPS 15',
    'HP Spectre x360',
    'Lenovo ThinkPad X1',
    'ASUS ROG Strix',
    'MacBook Air M3',
    'Dell Inspiron 15',
    'HP Pavilion 15',
    'Lenovo Yoga 9i',
    'ASUS ZenBook 14',
  ],
  tablets: [
    'iPad Pro 12.9-inch',
    'Samsung Galaxy Tab S9',
    'Microsoft Surface Pro 9',
    'iPad Air',
    'Samsung Galaxy Tab A9',
    'iPad 10th Gen',
    'Microsoft Surface Go 3',
    'Lenovo Tab P11',
    'Amazon Fire HD 10',
    'Huawei MatePad Pro',
  ],
  'audio-headphones': [
    'Sony WH-1000XM5',
    'Apple AirPods Pro 2',
    'Bose QuietComfort 45',
    'Sennheiser HD 660S',
    'Audio-Technica ATH-M50x',
    'Sony WF-1000XM4',
    'Apple AirPods Max',
    'Bose 700',
    'JBL Live 660NC',
    'Beats Studio3',
  ],
  cameras: [
    'Canon EOS R5',
    'Sony A7 IV',
    'Nikon Z9',
    'Fujifilm X-T5',
    'Panasonic Lumix GH6',
    'Canon EOS R6',
    'Sony A7 III',
    'Nikon Z6 II',
    'Fujifilm X-S20',
    'Olympus OM-1',
  ],
  gaming: [
    'PlayStation 5',
    'Xbox Series X',
    'Nintendo Switch OLED',
    'Steam Deck',
    'ASUS ROG Ally',
    'PlayStation 5 Digital',
    'Xbox Series S',
    'Nintendo Switch',
    'Valve Index VR',
    'Meta Quest 3',
  ],
  'smart-home': [
    'Amazon Echo Dot 5th Gen',
    'Google Nest Hub',
    'Philips Hue Starter Kit',
    'Ring Video Doorbell',
    'Nest Thermostat',
    'Amazon Echo Show 15',
    'Google Nest Mini',
    'SmartThings Hub',
    'Wyze Cam v3',
    'Eufy Security System',
  ],
  wearables: [
    'Apple Watch Series 9',
    'Samsung Galaxy Watch 6',
    'Fitbit Versa 4',
    'Garmin Venu 3',
    'Amazfit GTR 4',
    'Apple Watch SE',
    'Samsung Galaxy Watch 5',
    'Fitbit Charge 5',
    'Garmin Forerunner 265',
    'Polar Vantage M2',
  ],
  'electronics-accessories': [
    'Anker PowerCore 10000',
    'Belkin Boost Charge Pro',
    'Logitech MX Master 3S',
    'Corsair K70 RGB',
    'Razer DeathAdder V3',
    'Anker 65W Charger',
    'Belkin MagSafe Charger',
    'Logitech MX Keys',
    'SteelSeries Arctis 7P',
    'HyperX Cloud Alpha',
  ],
  components: [
    'Intel Core i9-13900K',
    'AMD Ryzen 9 7950X',
    'NVIDIA RTX 4090',
    'Corsair Vengeance DDR5',
    'Samsung 980 Pro SSD',
    'Intel Core i7-13700K',
    'AMD Ryzen 7 7700X',
    'NVIDIA RTX 4070',
    'G.Skill Trident Z5',
    'WD Black SN850X',
  ],

  // Clothing & Fashion
  'mens-clothing': [
    'Classic Oxford Shirt',
    'Slim Fit Chinos',
    'Merino Wool Sweater',
    'Denim Jacket',
    'Cotton Polo Shirt',
    'Tailored Blazer',
    'Cargo Pants',
    'Cashmere Scarf',
    'Leather Bomber Jacket',
    'Hooded Sweatshirt',
  ],
  'womens-clothing': [
    'Wrap Dress',
    'High-Waisted Jeans',
    'Silk Blouse',
    'Trench Coat',
    'Knit Cardigan',
    'Midi Skirt',
    'Crop Top',
    'Wool Coat',
    'Maxi Dress',
    'Blazer',
  ],
  'kids-clothing': [
    'Cartoon T-Shirt',
    'Denim Overalls',
    'Fleece Hoodie',
    'School Uniform',
    'Rain Jacket',
    'Graphic Tee',
    'Cargo Shorts',
    'Pajama Set',
    'Winter Coat',
    'Swim Trunks',
  ],
  shoes: [
    'Leather Oxford Shoes',
    'Running Sneakers',
    'Canvas Sneakers',
    'Ankle Boots',
    'Loafers',
    'High-Top Sneakers',
    'Chelsea Boots',
    'Sandals',
    'Dress Shoes',
    'Hiking Boots',
  ],
  'fashion-accessories': [
    'Leather Handbag',
    'Silk Scarf',
    'Gold Necklace',
    'Leather Belt',
    'Designer Sunglasses',
    'Crossbody Bag',
    'Cashmere Shawl',
    'Silver Bracelet',
    'Canvas Tote',
    'Aviator Sunglasses',
  ],
  'bags-purses': [
    'Leather Tote Bag',
    'Crossbody Purse',
    'Backpack',
    'Clutch Bag',
    'Messenger Bag',
    'Satchel Bag',
    'Hobo Bag',
    'Duffel Bag',
    'Evening Clutch',
    'Travel Backpack',
  ],
  activewear: [
    'Yoga Leggings',
    'Moisture-Wicking Tank',
    'Compression Shorts',
    'Sports Bra',
    'Running Jacket',
    'Athletic Shorts',
    'Performance Tee',
    'Bike Shorts',
    'Hoodie',
    'Windbreaker',
  ],
  'formal-wear': [
    'Business Suit',
    'Evening Gown',
    'Tuxedo',
    'Cocktail Dress',
    'Dress Shirt',
    'Blazer Set',
    'Formal Dress',
    'Dress Pants',
    'Blouse',
    'Tie Set',
  ],
  'underwear-lingerie': [
    'Cotton Briefs',
    'Lace Bra Set',
    'Boxer Briefs',
    'Silk Camisole',
    'Sports Bra',
    'Bikini Set',
    'Thermal Underwear',
    'Push-up Bra',
    'Boxer Shorts',
    'Chemise',
  ],
  'seasonal-clothing': [
    'Winter Parka',
    'Summer Dress',
    'Rain Jacket',
    'Fleece Jacket',
    'Swimwear',
    'Down Vest',
    'Sundress',
    'Windbreaker',
    'Thermal Shirt',
    'Beach Cover-up',
  ],

  // Home & Garden
  furniture: [
    'Modern Sofa',
    'Dining Table Set',
    'Bedroom Dresser',
    'Office Chair',
    'Coffee Table',
    'Sectional Couch',
    'Kitchen Island',
    'Nightstand',
    'Desk',
    'Bookshelf',
  ],
  'kitchen-dining': [
    'Stainless Steel Cookware Set',
    'Ceramic Dinnerware',
    'Kitchen Knife Set',
    'Coffee Maker',
    'Blender',
    'Non-Stick Pan Set',
    'Glassware Set',
    'Cutting Board',
    'Toaster',
    'Food Processor',
  ],
  'bedding-bath': [
    'Egyptian Cotton Sheets',
    'Down Comforter',
    'Bath Towel Set',
    'Memory Foam Pillow',
    'Shower Curtain',
    'Linen Bedding Set',
    'Weighted Blanket',
    'Bath Mat Set',
    'Pillowcase Set',
    'Bathrobe',
  ],
  'home-decor': [
    'Wall Art Print',
    'Decorative Vase',
    'Throw Pillow',
    'Table Lamp',
    'Mirror',
    'Candlestick Set',
    'Plant Pot',
    'Wall Clock',
    'Photo Frame',
    'Rug',
  ],
  lighting: [
    'LED Ceiling Light',
    'Table Lamp',
    'Floor Lamp',
    'Pendant Light',
    'String Lights',
    'Chandelier',
    'Desk Lamp',
    'Wall Sconce',
    'Track Lighting',
    'Solar Garden Lights',
  ],
  'storage-organization': [
    'Plastic Storage Bins',
    'Closet Organizer',
    'Shoe Rack',
    'Kitchen Pantry',
    'File Cabinet',
    'Under-Bed Storage',
    'Hanging Organizer',
    'Storage Ottoman',
    'Drawer Dividers',
    'Storage Baskets',
  ],
  'tools-hardware': [
    'Cordless Drill',
    'Tool Set',
    'Measuring Tape',
    'Level',
    'Screwdriver Set',
    'Hammer',
    'Wrench Set',
    'Safety Glasses',
    'Work Gloves',
    'Utility Knife',
  ],
  appliances: [
    'Refrigerator',
    'Washing Machine',
    'Dishwasher',
    'Microwave Oven',
    'Air Conditioner',
    'Dryer',
    'Stove',
    'Blender',
    'Vacuum Cleaner',
    'Iron',
  ],
  'cleaning-supplies': [
    'All-Purpose Cleaner',
    'Microfiber Cloths',
    'Vacuum Bags',
    'Dish Soap',
    'Laundry Detergent',
    'Glass Cleaner',
    'Sponges',
    'Broom Set',
    'Trash Bags',
    'Air Freshener',
  ],
  'safety-security': [
    'Smoke Detector',
    'Security Camera',
    'Door Lock',
    'Fire Extinguisher',
    'Motion Sensor',
    'Alarm System',
    'Deadbolt',
    'Carbon Monoxide Detector',
    'Security Light',
    'Window Sensor',
  ],

  // Sports & Outdoors
  'fitness-equipment': [
    'Adjustable Dumbbells',
    'Yoga Mat',
    'Resistance Bands',
    'Jump Rope',
    'Kettlebell',
    'Exercise Bike',
    'Treadmill',
    'Pull-up Bar',
    'Foam Roller',
    'Weight Bench',
  ],
  'outdoor-gear': [
    'Camping Tent',
    'Sleeping Bag',
    'Hiking Backpack',
    'Camping Stove',
    'Water Bottle',
    'Hiking Boots',
    'Camping Chair',
    'Headlamp',
    'Cooler',
    'First Aid Kit',
  ],
  'team-sports': [
    'Basketball',
    'Soccer Ball',
    'Volleyball',
    'Baseball Glove',
    'Tennis Racket',
    'Football',
    'Hockey Stick',
    'Badminton Set',
    'Ping Pong Paddle',
    'Golf Club Set',
  ],
  'water-sports': [
    'Swimming Goggles',
    'Snorkel Set',
    'Life Jacket',
    'Water Shoes',
    'Swim Fins',
    'Paddle Board',
    'Kayak',
    'Wetsuit',
    'Swimming Cap',
    'Waterproof Bag',
  ],
  'winter-sports': [
    'Ski Boots',
    'Snowboard',
    'Ski Goggles',
    'Winter Jacket',
    'Ski Gloves',
    'Snowshoes',
    'Ice Skates',
    'Thermal Underwear',
    'Ski Helmet',
    'Winter Hat',
  ],
  cycling: [
    'Mountain Bike',
    'Road Bike',
    'Bike Helmet',
    'Cycling Shorts',
    'Bike Lock',
    'Electric Bike',
    'Bike Lights',
    'Cycling Jersey',
    'Bike Pump',
    'Bike Rack',
  ],
  running: [
    'Running Shoes',
    'Running Shorts',
    'Moisture-Wicking Shirt',
    'Running Watch',
    'Hydration Belt',
    'Trail Running Shoes',
    'Compression Socks',
    'Running Hat',
    'GPS Watch',
    'Running Vest',
  ],
  golf: [
    'Golf Club Set',
    'Golf Balls',
    'Golf Glove',
    'Golf Bag',
    'Golf Shoes',
    'Putting Green',
    'Golf Tees',
    'Golf Rangefinder',
    'Golf Cart',
    'Golf Umbrella',
  ],
  'hunting-fishing': [
    'Fishing Rod',
    'Tackle Box',
    'Hunting Rifle',
    'Fishing Reel',
    'Hunting Knife',
    'Fishing Net',
    'Hunting Boots',
    'Fishing Line',
    'Hunting Vest',
    'Fishing Lures',
  ],
  'sports-apparel': [
    'Team Jersey',
    'Athletic Shorts',
    'Sports Bra',
    'Compression Shirt',
    'Team Cap',
    'Training Pants',
    'Performance Socks',
    'Team Jacket',
    'Athletic Shoes',
    'Team Bag',
  ],

  // Books & Media
  fiction: [
    'The Great Gatsby',
    'To Kill a Mockingbird',
    '1984',
    'Pride and Prejudice',
    'The Catcher in the Rye',
    'Lord of the Rings',
    'Harry Potter Series',
    'The Hobbit',
    'Dune',
    "The Handmaid's Tale",
  ],
  'non-fiction': [
    'Sapiens',
    'Atomic Habits',
    'Educated',
    'Becoming',
    'The Subtle Art of Not Giving a F*ck',
    'Thinking, Fast and Slow',
    'The Power of Now',
    'Born a Crime',
    'Outliers',
    'The 7 Habits',
  ],
  'childrens-books': [
    'Where the Wild Things Are',
    'The Very Hungry Caterpillar',
    'Goodnight Moon',
    "Charlotte's Web",
    'Harry Potter',
    'The Cat in the Hat',
    'Green Eggs and Ham',
    'The Giving Tree',
    'Corduroy',
    'Madeline',
  ],
  educational: [
    'Calculus Textbook',
    'Chemistry Lab Manual',
    'World History',
    'Biology Textbook',
    'Physics Guide',
    'Statistics Book',
    'Economics Textbook',
    'Psychology 101',
    'Literature Anthology',
    'Geography Atlas',
  ],
  'movies-tv': [
    'The Godfather DVD',
    'Breaking Bad Complete Series',
    'Star Wars Collection',
    'Marvel Cinematic Universe',
    'Game of Thrones',
    'The Office Complete Series',
    'Friends Box Set',
    'Pulp Fiction Blu-ray',
    'Inception DVD',
    'The Matrix Trilogy',
  ],
  music: [
    'Abbey Road Vinyl',
    'Thriller CD',
    'Dark Side of the Moon',
    'Kind of Blue',
    'Rumours',
    'Hotel California',
    'Back in Black',
    'The Wall',
    'Led Zeppelin IV',
    "Sgt. Pepper's",
  ],
  magazines: [
    'National Geographic',
    'Time Magazine',
    'Vogue',
    'Sports Illustrated',
    'The New Yorker',
    'Wired',
    'Rolling Stone',
    'People',
    'Forbes',
    'Architectural Digest',
  ],
  'comics-graphic-novels': [
    'Watchmen',
    'The Dark Knight Returns',
    'Maus',
    'Persepolis',
    'Saga Volume 1',
    'Sandman',
    'V for Vendetta',
    'Y: The Last Man',
    'Preacher',
    'Hellboy',
  ],
  audiobooks: [
    'The Martian Audiobook',
    'Born a Crime Audiobook',
    'Educated Audiobook',
    'Atomic Habits Audiobook',
    'Sapiens Audiobook',
    'Becoming Audiobook',
    'The Subtle Art Audiobook',
    'Thinking Fast and Slow Audiobook',
    'Outliers Audiobook',
    'The 7 Habits Audiobook',
  ],

  // Health & Beauty
  skincare: [
    'Vitamin C Serum',
    'Retinol Night Cream',
    'Hyaluronic Acid Moisturizer',
    'Sunscreen SPF 50',
    'Gentle Cleanser',
    'Anti-Aging Eye Cream',
    'Exfoliating Scrub',
    'Face Mask Set',
    'Toner',
    'Night Repair Serum',
  ],
  makeup: [
    'Foundation',
    'Mascara',
    'Lipstick Set',
    'Eyeshadow Palette',
    'Concealer',
    'Blush',
    'Eyeliner',
    'Highlighter',
    'Setting Powder',
    'Makeup Brushes',
  ],
  'hair-care': [
    'Shampoo & Conditioner Set',
    'Hair Dryer',
    'Hair Straightener',
    'Hair Oil',
    'Leave-in Conditioner',
    'Hair Mask',
    'Hair Brush Set',
    'Hair Spray',
    'Hair Vitamins',
    'Scalp Treatment',
  ],
  fragrances: [
    'Eau de Parfum',
    'Cologne',
    'Body Spray',
    'Perfume Gift Set',
    'Rollerball Perfume',
    'Solid Perfume',
    'Room Spray',
    'Candle Set',
    'Diffuser Oil',
    'Scented Lotion',
  ],
  'personal-care': [
    'Electric Toothbrush',
    'Body Wash',
    'Deodorant',
    'Razor Set',
    'Shaving Cream',
    'Toothpaste',
    'Mouthwash',
    'Body Lotion',
    'Hand Sanitizer',
    'Cotton Swabs',
  ],
  'health-supplements': [
    'Multivitamin',
    'Omega-3 Fish Oil',
    'Vitamin D3',
    'Probiotics',
    'Protein Powder',
    'Collagen Peptides',
    'Turmeric Curcumin',
    'Magnesium',
    'B-Complex',
    'Iron Supplement',
  ],
  'medical-supplies': [
    'First Aid Kit',
    'Digital Thermometer',
    'Blood Pressure Monitor',
    'Bandages',
    'Pain Relief Gel',
    'Antiseptic Solution',
    'Gauze Pads',
    'Medical Tape',
    'Ice Pack',
    'Hot Water Bottle',
  ],
  'fitness-wellness': [
    'Yoga Block Set',
    'Resistance Loop Bands',
    'Foam Roller',
    'Massage Gun',
    'Stretching Strap',
    'Balance Board',
    'Pilates Ring',
    'Meditation Cushion',
    'Essential Oils',
    'Sleep Mask',
  ],
  'mens-grooming': [
    'Beard Oil',
    'Electric Razor',
    'Aftershave Balm',
    'Face Scrub',
    'Styling Gel',
    'Beard Trimmer',
    'Pre-Shave Oil',
    'Moisturizer',
    'Hair Pomade',
    'Body Wash',
  ],
  'natural-organic': [
    'Organic Face Cream',
    'Natural Shampoo',
    'Herbal Tea Set',
    'Essential Oil Kit',
    'Organic Soap',
    'Natural Deodorant',
    'Organic Lip Balm',
    'Herbal Supplements',
    'Natural Toothpaste',
    'Organic Body Oil',
  ],

  // Automotive
  'car-parts': [
    'Brake Pads',
    'Oil Filter',
    'Air Filter',
    'Spark Plugs',
    'Battery',
    'Alternator',
    'Starter Motor',
    'Radiator',
    'Fuel Pump',
    'Timing Belt',
  ],
  'car-accessories': [
    'Car Phone Mount',
    'Dashboard Camera',
    'Car Charger',
    'Seat Covers',
    'Floor Mats',
    'Steering Wheel Cover',
    'Car Organizer',
    'Bluetooth Adapter',
    'Car Vacuum',
    'Tire Pressure Gauge',
  ],
  'automotive-tools': [
    'Socket Wrench Set',
    'Jack Stands',
    'Car Jack',
    'Torque Wrench',
    'Multimeter',
    'OBD2 Scanner',
    'Funnel Set',
    'Gloves',
    'Safety Glasses',
    'Work Light',
  ],
  'oils-fluids': [
    'Motor Oil 5W-30',
    'Brake Fluid',
    'Coolant',
    'Transmission Fluid',
    'Power Steering Fluid',
    'Windshield Washer Fluid',
    'Gear Oil',
    'Hydraulic Fluid',
    'Synthetic Oil',
    'Oil Additive',
  ],
  'tires-wheels': [
    'All-Season Tires',
    'Winter Tires',
    'Tire Chains',
    'Wheel Covers',
    'Tire Pressure Monitor',
    'Summer Tires',
    'Tire Repair Kit',
    'Wheel Spacers',
    'Tire Inflator',
    'Tire Rotation Kit',
  ],
  'automotive-interior': [
    'Car Seat Covers',
    'Dashboard Mat',
    'Cup Holders',
    'Storage Organizer',
    'Air Freshener',
    'Steering Wheel Cover',
    'Gear Shift Knob',
    'Pedal Covers',
    'Window Shades',
    'Trunk Organizer',
  ],
  'automotive-exterior': [
    'Car Cover',
    'Mud Flaps',
    'Hood Protector',
    'Side Mirrors',
    'License Plate Frame',
    'Car Wash Kit',
    'Wax Kit',
    'Chrome Trim',
    'Door Handles',
    'Grille Guard',
  ],
  'automotive-electronics': [
    'Car Stereo',
    'Bluetooth Speaker',
    'GPS Navigation',
    'Backup Camera',
    'LED Headlights',
    'Car Amplifier',
    'Subwoofer',
    'USB Charger',
    'FM Transmitter',
    'Dash Cam',
  ],
  'automotive-maintenance': [
    'Car Wash Soap',
    'Wax Kit',
    'Tire Shine',
    'Engine Degreaser',
    'Glass Cleaner',
    'Interior Cleaner',
    'Leather Conditioner',
    'Rust Inhibitor',
    'Fuel Injector Cleaner',
    'Coolant Flush',
  ],
  motorcycle: [
    'Motorcycle Helmet',
    'Riding Gloves',
    'Motorcycle Jacket',
    'Riding Boots',
    'Motorcycle Cover',
    'Chain Lube',
    'Motorcycle Oil',
    'Air Filter',
    'Spark Plugs',
    'Brake Pads',
  ],

  // Toys & Games
  'action-figures': [
    'Superhero Action Figure',
    'Star Wars Figure',
    'Marvel Legends',
    'Transformers',
    'G.I. Joe',
    'Batman Figure',
    'Spider-Man Figure',
    'Avengers Set',
    'Ninja Turtles',
    'Power Rangers',
  ],
  'board-games': [
    'Monopoly',
    'Settlers of Catan',
    'Ticket to Ride',
    'Pandemic',
    'Codenames',
    'Azul',
    'Wingspan',
    'Gloomhaven',
    'Splendor',
    '7 Wonders',
  ],
  puzzles: [
    '1000-Piece Jigsaw Puzzle',
    '3D Puzzle',
    'Crossword Puzzle Book',
    'Sudoku Book',
    'Brain Teasers',
    '500-Piece Puzzle',
    'Wooden Puzzle',
    'Logic Puzzle',
    'Word Search',
    "Rubik's Cube",
  ],
  'educational-toys': [
    'Building Blocks Set',
    'Science Kit',
    'Math Learning Game',
    'Coding Robot',
    'Microscope',
    'Telescope',
    'Chemistry Set',
    'Geography Puzzle',
    'Language Learning Game',
    'Art Supplies Kit',
  ],
  'electronic-toys': [
    'Remote Control Car',
    'Drone',
    'Robot Dog',
    'Electronic Keyboard',
    'Gaming Console',
    'Virtual Reality Headset',
    'Smart Watch for Kids',
    'Electronic Drawing Tablet',
    'Walkie Talkies',
    'Electronic Pet',
  ],
  'outdoor-toys': [
    'Trampoline',
    'Swing Set',
    'Bicycle',
    'Scooter',
    'Skateboard',
    'Basketball Hoop',
    'Soccer Goal',
    'Playhouse',
    'Sandbox',
    'Water Slide',
  ],
  'toys-arts-crafts': [
    'Art Set',
    'Craft Kit',
    'Coloring Books',
    'Play-Doh Set',
    'Beading Kit',
    'Painting Set',
    'Origami Kit',
    'Jewelry Making Kit',
    'Pottery Kit',
    'Sewing Kit',
  ],
  'dolls-stuffed-animals': [
    'Barbie Doll',
    'Teddy Bear',
    'American Girl Doll',
    'Stuffed Elephant',
    'Baby Doll',
    'Plush Unicorn',
    'Dollhouse',
    'Stuffed Dog',
    'Fashion Doll',
    'Interactive Pet',
  ],
  'building-sets': [
    'LEGO Classic Set',
    'Magnetic Tiles',
    'Wooden Blocks',
    "K'NEX Set",
    'Marble Run',
    'LEGO Creator Set',
    'Building Straws',
    'Lincoln Logs',
    'Tinkertoys',
    'Gears Set',
  ],
  'video-games': [
    'Nintendo Switch Game',
    'PlayStation 5 Game',
    'Xbox Game',
    'PC Game',
    'Mobile Game',
    'Retro Game Console',
    'Gaming Headset',
    'Gaming Controller',
    'Gaming Mouse',
    'Gaming Keyboard',
  ],

  // Food & Beverages
  'fresh-produce': [
    'Organic Bananas',
    'Fresh Strawberries',
    'Avocados',
    'Spinach',
    'Bell Peppers',
    'Apples',
    'Carrots',
    'Broccoli',
    'Tomatoes',
    'Lettuce',
  ],
  'meat-seafood': [
    'Grass-Fed Beef',
    'Free-Range Chicken',
    'Wild Salmon',
    'Ground Turkey',
    'Pork Chops',
    'Shrimp',
    'Lamb Chops',
    'Tuna Steak',
    'Bacon',
    'Sausage',
  ],
  'dairy-eggs': [
    'Organic Milk',
    'Free-Range Eggs',
    'Greek Yogurt',
    'Cheddar Cheese',
    'Butter',
    'Cottage Cheese',
    'Mozzarella',
    'Cream Cheese',
    'Sour Cream',
    'Heavy Cream',
  ],
  'pantry-staples': [
    'Extra Virgin Olive Oil',
    'Quinoa',
    'Brown Rice',
    'Canned Tomatoes',
    'Black Beans',
    'Pasta',
    'Coconut Oil',
    'Honey',
    'Sea Salt',
    'Black Pepper',
  ],
  beverages: [
    'Sparkling Water',
    'Green Tea',
    'Coffee Beans',
    'Fresh Orange Juice',
    'Kombucha',
    'Herbal Tea',
    'Coconut Water',
    'Protein Shake',
    'Energy Drink',
    'Wine',
  ],
  snacks: [
    'Almonds',
    'Dark Chocolate',
    'Popcorn',
    'Trail Mix',
    'Granola Bars',
    'Chips',
    'Nuts',
    'Dried Fruit',
    'Crackers',
    'Cookies',
  ],
  'frozen-foods': [
    'Frozen Berries',
    'Frozen Pizza',
    'Ice Cream',
    'Frozen Vegetables',
    'Frozen Yogurt',
    'Frozen Meals',
    'Frozen Fish',
    'Frozen Chicken',
    'Frozen Fruit',
    'Frozen Waffles',
  ],
  bakery: [
    'Artisan Bread',
    'Croissants',
    'Muffins',
    'Bagels',
    'Cake',
    'Cookies',
    'Donuts',
    'Pie',
    'Scones',
    'Biscuits',
  ],
  'international-food': [
    'Thai Curry Paste',
    'Italian Pasta',
    'Mexican Salsa',
    'Indian Spices',
    'Japanese Rice',
    'Chinese Noodles',
    'Mediterranean Olives',
    'French Cheese',
    'German Sausage',
    'Korean Kimchi',
  ],
  'organic-natural-food': [
    'Organic Honey',
    'Natural Peanut Butter',
    'Organic Cereal',
    'Raw Nuts',
    'Superfood Powder',
    'Organic Granola',
    'Natural Jam',
    'Raw Cacao',
    'Organic Coconut',
    'Natural Sweetener',
  ],

  // Jewelry & Watches
  rings: [
    'Gold Wedding Band',
    'Diamond Engagement Ring',
    'Silver Signet Ring',
    'Pearl Ring',
    'Sapphire Ring',
    'Platinum Band',
    'Emerald Ring',
    'Titanium Ring',
    'Rose Gold Ring',
    'Vintage Ring',
  ],
  necklaces: [
    'Pearl Necklace',
    'Gold Chain',
    'Diamond Pendant',
    'Silver Locket',
    'Charm Necklace',
    'Crystal Necklace',
    'Cross Pendant',
    'Initial Necklace',
    'Layering Necklaces',
    'Statement Necklace',
  ],
  earrings: [
    'Diamond Studs',
    'Pearl Earrings',
    'Gold Hoops',
    'Silver Drops',
    'Crystal Earrings',
    'Huggie Earrings',
    'Chandelier Earrings',
    'Threader Earrings',
    'Clip-On Earrings',
    'Ear Cuffs',
  ],
  bracelets: [
    'Gold Bangle',
    'Silver Chain Bracelet',
    'Pearl Bracelet',
    'Charm Bracelet',
    'Leather Wrap',
    'Tennis Bracelet',
    'Cuff Bracelet',
    'Beaded Bracelet',
    'ID Bracelet',
    'Friendship Bracelet',
  ],
  watches: [
    'Swiss Watch',
    'Smart Watch',
    'Dive Watch',
    'Dress Watch',
    'Sports Watch',
    'Luxury Watch',
    'Vintage Watch',
    'Digital Watch',
    'Chronograph Watch',
    'Minimalist Watch',
  ],
  'brooches-pins': [
    'Vintage Brooch',
    'Enamel Pin',
    'Crystal Brooch',
    'Lapel Pin',
    'Statement Brooch',
    'Pearl Brooch',
    'Art Deco Pin',
    'Floral Brooch',
    'Animal Pin',
    'Collectible Pin',
  ],
  anklets: [
    'Gold Anklet',
    'Silver Chain Anklet',
    'Beaded Anklet',
    'Charm Anklet',
    'Leather Anklet',
    'Crystal Anklet',
    'Pearl Anklet',
    'Adjustable Anklet',
    'Delicate Anklet',
    'Boho Anklet',
  ],
  'body-jewelry': [
    'Nose Ring',
    'Belly Button Ring',
    'Ear Gauges',
    'Tongue Ring',
    'Cartilage Stud',
    'Septum Ring',
    'Industrial Bar',
    'Helix Ring',
    'Tragus Stud',
    'Rook Ring',
  ],
  'jewelry-sets': [
    'Pearl Jewelry Set',
    'Diamond Set',
    'Gold Jewelry Set',
    'Silver Set',
    'Crystal Set',
    'Wedding Jewelry Set',
    'Bridal Set',
    'Evening Set',
    'Casual Set',
    'Luxury Set',
  ],
  'jewelry-care': [
    'Jewelry Cleaner',
    'Jewelry Box',
    'Jewelry Organizer',
    'Polishing Cloth',
    'Ultrasonic Cleaner',
    'Jewelry Display',
    'Travel Case',
    'Anti-Tarnish Strips',
    'Jewelry Scale',
    'Magnifying Glass',
  ],

  // Office Supplies
  'writing-instruments': [
    'Ballpoint Pen Set',
    'Fountain Pen',
    'Mechanical Pencil',
    'Highlighter Set',
    'Marker Set',
    'Gel Pen',
    'Rollerball Pen',
    'Calligraphy Pen',
    'Sharpie Set',
    'Whiteboard Marker',
  ],
  'paper-notebooks': [
    'Spiral Notebook',
    'Legal Pad',
    'Sticky Notes',
    'Copy Paper',
    'Notebook Set',
    'Journal',
    'Planner',
    'Index Cards',
    'Graph Paper',
    'Colored Paper',
  ],
  'filing-organization': [
    'File Folders',
    'Binder Set',
    'Label Maker',
    'Desk Organizer',
    'File Cabinet',
    'Storage Boxes',
    'Hanging Files',
    'Tab Dividers',
    'Document Holder',
    'Mail Organizer',
  ],
  'desk-accessories': [
    'Desk Lamp',
    'Pen Holder',
    'Paperweight',
    'Desk Calendar',
    'Mouse Pad',
    'Monitor Stand',
    'Cable Organizer',
    'Desk Mat',
    'Business Card Holder',
    'Letter Tray',
  ],
  'office-technology': [
    'Wireless Mouse',
    'Keyboard',
    'Monitor',
    'Printer',
    'Scanner',
    'Webcam',
    'Headset',
    'USB Hub',
    'External Hard Drive',
    'Surge Protector',
  ],
  presentation: [
    'Flip Chart',
    'Whiteboard',
    'Projector Screen',
    'Presentation Remote',
    'Easel',
    'Bulletin Board',
    'Poster Board',
    'Transparency Sheets',
    'Laser Pointer',
    'Presentation Folder',
  ],
  'shipping-mailing': [
    'Shipping Boxes',
    'Bubble Wrap',
    'Packing Tape',
    'Shipping Labels',
    'Envelopes',
    'Mailer Bags',
    'Packing Peanuts',
    'Address Labels',
    'Postage Scale',
    'Return Labels',
  ],
  'break-room': [
    'Coffee Maker',
    'Water Cooler',
    'Microwave',
    'Refrigerator',
    'Coffee Cups',
    'Paper Plates',
    'Utensils',
    'Napkins',
    'Coffee Filters',
    'Snack Dispenser',
  ],
  'office-safety-security': [
    'Fire Extinguisher',
    'First Aid Kit',
    'Safety Glasses',
    'Hard Hat',
    'Reflective Vest',
    'Lock Box',
    'Security Camera',
    'Access Card',
    'Emergency Kit',
    'Safety Sign',
  ],
  'office-cleaning': [
    'All-Purpose Cleaner',
    'Paper Towels',
    'Trash Bags',
    'Vacuum Cleaner',
    'Dusting Cloths',
    'Glass Cleaner',
    'Disinfectant Wipes',
    'Mop',
    'Broom',
    'Air Freshener',
  ],

  // Pet Supplies
  'dog-supplies': [
    'Dog Food',
    'Dog Leash',
    'Dog Collar',
    'Dog Toys',
    'Dog Bed',
    'Dog Treats',
    'Dog Bowl',
    'Dog Shampoo',
    'Dog Brush',
    'Dog Crate',
  ],
  'cat-supplies': [
    'Cat Food',
    'Cat Litter',
    'Cat Toys',
    'Cat Bed',
    'Cat Scratching Post',
    'Cat Treats',
    'Cat Bowl',
    'Cat Carrier',
    'Cat Brush',
    'Cat Tree',
  ],
  'fish-aquarium': [
    'Fish Tank',
    'Fish Food',
    'Aquarium Filter',
    'Aquarium Heater',
    'Fish Net',
    'Aquarium Decorations',
    'Water Conditioner',
    'Fish Bowl',
    'Aquarium Gravel',
    'Air Pump',
  ],
  'bird-supplies': [
    'Bird Cage',
    'Bird Food',
    'Bird Toys',
    'Bird Perch',
    'Bird Treats',
    'Bird Bath',
    'Bird Seed',
    'Bird Swing',
    'Bird Mirror',
    'Bird Ladder',
  ],
  'small-pets': [
    'Hamster Cage',
    'Rabbit Food',
    'Guinea Pig Bedding',
    'Small Pet Toys',
    'Pet Carrier',
    'Small Pet Treats',
    'Exercise Wheel',
    'Water Bottle',
    'Food Bowl',
    'Pet Bed',
  ],
  'reptile-supplies': [
    'Terrarium',
    'Reptile Food',
    'Heat Lamp',
    'UVB Bulb',
    'Reptile Substrate',
    'Reptile Decor',
    'Thermometer',
    'Hygrometer',
    'Reptile Hide',
    'Feeding Tongs',
  ],
  'pet-health': [
    'Pet Vitamins',
    'Flea Treatment',
    'Pet Grooming Kit',
    'Pet Nail Clippers',
    'Pet Toothbrush',
    'Pet Shampoo',
    'Pet Wipes',
    'Pet Ear Cleaner',
    'Pet Eye Drops',
    'Pet First Aid Kit',
  ],
  'pet-training': [
    'Training Treats',
    'Clicker',
    'Training Pads',
    'Pet Whistle',
    'Training Collar',
    'Pet Clicker',
    'Training Guide',
    'Pet Reward System',
    'Training Mat',
    'Pet Commands',
  ],
  'pet-travel': [
    'Pet Carrier',
    'Travel Bowl',
    'Pet Seat Belt',
    'Travel Crate',
    'Pet Passport',
    'Travel Water Bottle',
    'Pet Travel Bag',
    'Car Seat Cover',
    'Pet ID Tag',
    'Travel Litter Box',
  ],
  'pet-furniture': [
    'Pet Bed',
    'Cat Tree',
    'Dog House',
    'Pet Sofa',
    'Pet Hammock',
    'Pet Couch',
    'Pet Chair',
    'Pet Stairs',
    'Pet Gate',
    'Pet Playpen',
  ],

  // Baby & Kids
  'baby-clothing': [
    'Onesie Set',
    'Baby Romper',
    'Sleep Gown',
    'Baby Pants',
    'Baby Hat',
    'Baby Socks',
    'Baby Mittens',
    'Baby Bibs',
    'Baby Jacket',
    'Baby Dress',
  ],
  diapering: [
    'Diapers',
    'Baby Wipes',
    'Diaper Rash Cream',
    'Changing Pad',
    'Diaper Bag',
    'Diaper Pail',
    'Diaper Covers',
    'Changing Table',
    'Diaper Disposal',
    'Diaper Organizer',
  ],
  'baby-feeding': [
    'Baby Bottles',
    'Baby Formula',
    'Sippy Cups',
    'Baby Spoons',
    'High Chair',
    'Bottle Warmer',
    'Baby Food',
    'Bibs',
    'Burp Cloths',
    'Feeding Set',
  ],
  nursery: [
    'Crib',
    'Crib Mattress',
    'Nursery Glider',
    'Changing Table',
    'Dresser',
    'Night Light',
    'Mobile',
    'Nursery Decor',
    'Blackout Curtains',
    'Nursery Rug',
  ],
  'baby-safety': [
    'Baby Monitor',
    'Outlet Covers',
    'Safety Gates',
    'Corner Guards',
    'Cabinet Locks',
    'Car Seat',
    'Baby Proofing Kit',
    'Door Knob Covers',
    'Window Guards',
    'Safety Straps',
  ],
  'baby-toys-play': [
    'Rattle',
    'Teething Toy',
    'Activity Gym',
    'Soft Blocks',
    'Musical Toy',
    'Stacking Rings',
    'Shape Sorter',
    'Baby Book',
    'Bath Toys',
    'Play Mat',
  ],
  'baby-bath-grooming': [
    'Baby Bathtub',
    'Baby Shampoo',
    'Hooded Towel',
    'Baby Lotion',
    'Baby Brush',
    'Nail Clippers',
    'Thermometer',
    'Baby Oil',
    'Bath Toys',
    'Washcloths',
  ],
  'baby-travel': [
    'Stroller',
    'Car Seat',
    'Baby Carrier',
    'Travel Crib',
    'Diaper Bag',
    'Baby Travel Kit',
    'Portable High Chair',
    'Travel Stroller',
    'Car Seat Cover',
    'Travel Toys',
  ],
  'baby-health': [
    'Baby Thermometer',
    'Nasal Aspirator',
    'Baby Medicine',
    'First Aid Kit',
    'Baby Vitamins',
    'Teething Gel',
    'Baby Saline Drops',
    'Baby Probiotics',
    'Baby Sunscreen',
    'Baby Tylenol',
  ],
  'baby-gear-equipment': [
    'Baby Swing',
    'Bouncer',
    'Playpen',
    'Baby Walker',
    'Jump-a-roo',
    'Baby Rocker',
    'Activity Center',
    'Baby Gym',
    'Tummy Time Mat',
    'Baby Seat',
  ],

  // Travel & Luggage
  luggage: [
    'Carry-On Suitcase',
    'Checked Luggage',
    'Duffel Bag',
    'Garment Bag',
    'Hard Shell Suitcase',
    'Soft Side Luggage',
    'Spinner Luggage',
    'Travel Backpack',
    'Weekend Bag',
    'Luggage Set',
  ],
  'travel-backpacks': [
    'Hiking Backpack',
    'Travel Backpack',
    'Daypack',
    'Laptop Backpack',
    'Camera Backpack',
    'School Backpack',
    'Commuter Backpack',
    'Tactical Backpack',
    'Rolling Backpack',
    'Hydration Pack',
  ],
  'travel-accessories': [
    'Packing Cubes',
    'Travel Organizer',
    'Luggage Scale',
    'Luggage Tags',
    'Travel Locks',
    'Compression Bags',
    'Shoe Bags',
    'Travel Pillow',
    'Eye Mask',
    'Ear Plugs',
  ],
  'travel-electronics': [
    'Universal Adapter',
    'Portable Charger',
    'Travel Router',
    'Noise Canceling Headphones',
    'Travel Speaker',
    'Tablet Stand',
    'Cable Organizer',
    'Travel Camera',
    'GPS Device',
    'Travel Alarm Clock',
  ],
  'travel-comfort': [
    'Neck Pillow',
    'Travel Blanket',
    'Compression Socks',
    'Travel Slippers',
    'Eye Mask',
    'Travel Pillow',
    'Comfort Kit',
    'Travel Hammock',
    'Portable Fan',
    'Travel Yoga Mat',
  ],
  'travel-security': [
    'Travel Locks',
    'RFID Wallet',
    'Money Belt',
    'Travel Safe',
    'Luggage Tracker',
    'Security Cable',
    'Travel Door Alarm',
    'Personal Alarm',
    'Travel Insurance',
    'Emergency Kit',
  ],
  'outdoor-travel': [
    'Camping Tent',
    'Sleeping Bag',
    'Camping Stove',
    'Hiking Boots',
    'Camping Chair',
    'Portable Water Filter',
    'Camping Lantern',
    'Hiking Poles',
    'Camping Table',
    'Outdoor Cookware',
  ],
  'business-travel': [
    'Business Briefcase',
    'Laptop Sleeve',
    'Travel Portfolio',
    'Business Card Holder',
    'Travel Iron',
    'Garment Steamer',
    'Travel Shoe Shine',
    'Business Travel Kit',
    'Travel Umbrella',
    'Professional Attire',
  ],
  'travel-documents': [
    'Passport Holder',
    'Travel Wallet',
    'Document Organizer',
    'Travel Folder',
    'ID Holder',
    'Travel Checklist',
    'Visa Holder',
    'Travel Insurance Card',
    'Boarding Pass Holder',
    'Travel Journal',
  ],
  'travel-gift-souvenirs': [
    'Local Artisan Craft',
    'Travel Magnet',
    'Postcard Set',
    'Local Specialty Food',
    'Travel T-Shirt',
    'Cultural Souvenir',
    'Travel Photo Frame',
    'Local Jewelry',
    'Travel Mug',
    'Destination Guide',
  ],

  // Musical Instruments
  guitars: [
    'Acoustic Guitar',
    'Electric Guitar',
    'Classical Guitar',
    'Bass Guitar',
    '12-String Guitar',
    'Travel Guitar',
    'Guitar Starter Pack',
    'Guitar Amplifier',
    'Guitar Strings',
    'Guitar Case',
  ],
  'pianos-keyboards': [
    'Digital Piano',
    'Electronic Keyboard',
    'Synthesizer',
    'MIDI Controller',
    'Piano Bench',
    'Piano Stool',
    'Keyboard Stand',
    'Piano Lamp',
    'Metronome',
    'Piano Books',
  ],
  'drums-percussion': [
    'Drum Set',
    'Snare Drum',
    'Cymbal Set',
    'Drum Sticks',
    'Drum Throne',
    'Electronic Drums',
    'Percussion Kit',
    'Djembe',
    'Bongo Drums',
    'Tambourine',
  ],
  'brass-instruments': [
    'Trumpet',
    'Trombone',
    'French Horn',
    'Tuba',
    'Cornet',
    'Flugelhorn',
    'Baritone Horn',
    'Mouthpiece',
    'Valve Oil',
    'Brass Polish',
  ],
  'woodwind-instruments': [
    'Flute',
    'Clarinet',
    'Saxophone',
    'Oboe',
    'Bassoon',
    'Recorder',
    'Piccolo',
    'Reeds',
    'Cork Grease',
    'Swab',
  ],
  'string-instruments': [
    'Violin',
    'Viola',
    'Cello',
    'Double Bass',
    'Harp',
    'Mandolin',
    'Banjo',
    'Ukulele',
    'Bow',
    'Rosin',
  ],
  'music-accessories': [
    'Music Stand',
    'Tuner',
    'Metronome',
    'Capo',
    'Guitar Picks',
    'Instrument Case',
    'Strap',
    'Cable',
    'Effects Pedal',
    'Microphone',
  ],
  'audio-equipment': [
    'Amplifier',
    'Speaker',
    'Mixing Board',
    'Microphone',
    'Headphones',
    'Audio Interface',
    'Studio Monitors',
    'PA System',
    'Wireless System',
    'Audio Cable',
  ],
  'recording-equipment': [
    'Audio Interface',
    'Studio Microphone',
    'Pop Filter',
    'Shock Mount',
    'Audio Software',
    'MIDI Keyboard',
    'Audio Cable',
    'Studio Headphones',
    'Recording Software',
    'Audio Mixer',
  ],
  'sheet-music': [
    'Piano Sheet Music',
    'Guitar Tab Book',
    'Orchestra Score',
    'Choir Music',
    'Method Book',
    'Songbook',
    'Theory Book',
    'Exercise Book',
    'Composition Book',
    'Music Dictionary',
  ],

  // Art & Crafts
  drawing: [
    'Sketchbook',
    'Pencil Set',
    'Charcoal Set',
    'Drawing Paper',
    'Eraser Set',
    'Blending Stumps',
    'Fixative Spray',
    'Drawing Board',
    'Pencil Sharpener',
    'Art Portfolio',
  ],
  painting: [
    'Acrylic Paint Set',
    'Watercolor Set',
    'Oil Paint Set',
    'Paint Brushes',
    'Canvas',
    'Easel',
    'Palette',
    'Paint Mediums',
    'Varnish',
    'Painting Knives',
  ],
  sculpting: [
    'Modeling Clay',
    'Sculpting Tools',
    'Pottery Wheel',
    'Kiln',
    'Ceramic Glazes',
    'Wire Armature',
    'Sculpting Stand',
    'Clay Tools',
    'Firing Supplies',
    'Pottery Kit',
  ],
  'paper-crafts': [
    'Scrapbook Paper',
    'Cardstock',
    'Origami Paper',
    'Paper Punches',
    'Adhesive',
    'Scrapbook Kit',
    'Paper Trimmer',
    'Embellishments',
    'Stickers',
    'Washi Tape',
  ],
  'fabric-textiles': [
    'Cotton Fabric',
    'Sewing Machine',
    'Thread Set',
    'Fabric Scissors',
    'Pattern',
    'Yarn Set',
    'Knitting Needles',
    'Crochet Hooks',
    'Fabric Markers',
    'Sewing Kit',
  ],
  'jewelry-making': [
    'Beading Kit',
    'Jewelry Wire',
    'Pliers Set',
    'Beads',
    'Jewelry Findings',
    'Chain',
    'Clasps',
    'Jump Rings',
    'Crimp Beads',
    'Jewelry Tools',
  ],
  woodworking: [
    'Wood Chisels',
    'Hand Saw',
    'Wood Glue',
    'Sandpaper Set',
    'Wood Clamps',
    'Router',
    'Wood Stain',
    'Wood Finish',
    'Measuring Tools',
    'Safety Equipment',
  ],
  scrapbooking: [
    'Scrapbook Album',
    'Photo Paper',
    'Decorative Paper',
    'Embellishments',
    'Adhesive',
    'Scrapbook Kit',
    'Photo Corners',
    'Journaling Cards',
    'Stamps',
    'Ink Pads',
  ],
  'candle-making': [
    'Candle Wax',
    'Wicks',
    'Candle Molds',
    'Fragrance Oils',
    'Dye Chips',
    'Melting Pot',
    'Thermometer',
    'Pouring Pot',
    'Candle Jars',
    'Wick Centering Device',
  ],
  'craft-tools-equipment': [
    'Hot Glue Gun',
    'Craft Knife',
    'Cutting Mat',
    'Ruler',
    'Tweezers',
    'Craft Scissors',
    'Bone Folder',
    'Embossing Tool',
    'Heat Gun',
    'Craft Storage',
  ],

  // Industrial & Scientific
  'lab-equipment': [
    'Microscope',
    'Test Tubes',
    'Beakers',
    'Lab Coat',
    'Safety Goggles',
    'Bunsen Burner',
    'Graduated Cylinder',
    'Petri Dishes',
    'Lab Balance',
    'pH Meter',
  ],
  'measuring-tools': [
    'Digital Caliper',
    'Tape Measure',
    'Level',
    'Protractor',
    'Ruler Set',
    'Micrometer',
    'Angle Gauge',
    'Laser Measure',
    'Precision Scale',
    'Measuring Wheel',
  ],
  'safety-equipment': [
    'Hard Hat',
    'Safety Glasses',
    'Work Gloves',
    'Safety Vest',
    'Respirator',
    'Ear Protection',
    'Safety Boots',
    'Fall Protection',
    'First Aid Kit',
    'Emergency Shower',
  ],
  'power-tools': [
    'Cordless Drill',
    'Circular Saw',
    'Angle Grinder',
    'Impact Driver',
    'Reciprocating Saw',
    'Jigsaw',
    'Router',
    'Sander',
    'Nail Gun',
    'Power Screwdriver',
  ],
  fasteners: [
    'Screw Set',
    'Bolt Set',
    'Nail Set',
    'Rivet Set',
    'Washer Set',
    'Nut Set',
    'Anchor Set',
    'Staple Set',
    'Clip Set',
    'Fastener Kit',
  ],
  'electrical-supplies': [
    'Wire',
    'Electrical Outlet',
    'Switch',
    'Circuit Breaker',
    'Electrical Box',
    'Cable',
    'Connector',
    'Fuse',
    'Electrical Tape',
    'Wire Nuts',
  ],
  'plumbing-supplies': [
    'Pipe',
    'Fitting',
    'Valve',
    'Faucet',
    'Toilet',
    'Sink',
    'Shower Head',
    'Pipe Wrench',
    "Plumber's Tape",
    'Pipe Insulation',
  ],
  hvac: [
    'Air Filter',
    'Thermostat',
    'Ductwork',
    'Vent Cover',
    'HVAC Unit',
    'Heat Pump',
    'Air Conditioner',
    'Furnace',
    'Duct Tape',
    'Insulation',
  ],
  'industrial-materials': [
    'Steel Sheet',
    'Aluminum Bar',
    'Plastic Sheet',
    'Rubber Mat',
    'Fiberglass',
    'Carbon Fiber',
    'Ceramic Tile',
    'Concrete Mix',
    'Insulation',
    'Adhesive',
  ],
  'testing-equipment': [
    'Multimeter',
    'Oscilloscope',
    'Signal Generator',
    'Power Supply',
    'Function Generator',
    'Logic Analyzer',
    'Spectrum Analyzer',
    'Network Analyzer',
    'Calibration Kit',
    'Test Leads',
  ],

  // Garden & Outdoor
  'garden-tools': [
    'Garden Spade',
    'Pruning Shears',
    'Garden Hoe',
    'Rake',
    'Garden Fork',
    'Watering Can',
    'Garden Gloves',
    'Trowel',
    'Garden Knife',
    'Wheelbarrow',
  ],
  'plants-seeds': [
    'Flower Seeds',
    'Vegetable Seeds',
    'Herb Seeds',
    'Plant Pots',
    'Seedling Trays',
    'Potting Soil',
    'Fertilizer',
    'Plant Food',
    'Garden Soil',
    'Compost',
  ],
  'outdoor-furniture': [
    'Patio Table',
    'Garden Chairs',
    'Outdoor Sofa',
    'Garden Bench',
    'Hammock',
    'Outdoor Cushions',
    'Garden Umbrella',
    'Outdoor Storage',
    'Fire Pit',
    'Outdoor Rug',
  ],
  'grills-bbq': [
    'Gas Grill',
    'Charcoal Grill',
    'BBQ Tools',
    'Grill Cover',
    'Grill Brush',
    'BBQ Sauce',
    'Grill Mat',
    'Smoker',
    'Grill Pan',
    'BBQ Thermometer',
  ],
  'outdoor-lighting': [
    'Solar Lights',
    'LED String Lights',
    'Garden Spotlights',
    'Pathway Lights',
    'Deck Lights',
    'Outdoor Chandelier',
    'Motion Sensor Light',
    'Landscape Lighting',
    'Pool Lights',
    'Security Lights',
  ],
  'water-features': [
    'Fountain',
    'Pond Kit',
    'Water Pump',
    'Waterfall Kit',
    'Bird Bath',
    'Water Feature',
    'Pond Filter',
    'Aquatic Plants',
    'Pond Liner',
    'Water Treatment',
  ],
  'pest-control': [
    'Insecticide',
    'Pest Repellent',
    'Garden Spray',
    'Pest Trap',
    'Organic Pesticide',
    'Bug Zapper',
    'Pest Barrier',
    'Natural Repellent',
    'Pest Control Kit',
    'Garden Netting',
  ],
  'outdoor-storage': [
    'Garden Shed',
    'Storage Box',
    'Tool Rack',
    'Garden Cabinet',
    'Storage Bench',
    'Deck Box',
    'Storage Bins',
    'Tool Organizer',
    'Garden Cart',
    'Storage Rack',
  ],
  'garden-decorative': [
    'Garden Statue',
    'Wind Chime',
    'Garden Gnome',
    'Decorative Pot',
    'Garden Sign',
    'Bird Feeder',
    'Garden Ornament',
    'Decorative Rock',
    'Garden Art',
    'Plant Markers',
  ],
  'garden-seasonal': [
    'Christmas Lights',
    'Halloween Decorations',
    'Spring Planters',
    'Fall Decorations',
    'Holiday Wreath',
    'Seasonal Flags',
    'Garden Flags',
    'Holiday Planters',
    'Seasonal Ornaments',
    'Holiday Lighting',
  ],

  // Collectibles
  antiques: [
    'Vintage Clock',
    'Antique Vase',
    'Collectible Plate',
    'Vintage Jewelry',
    'Antique Furniture',
    'Vintage Poster',
    'Antique Book',
    'Collectible Figurine',
    'Vintage Camera',
    'Antique Silver',
  ],
  'coins-currency': [
    'Silver Coin',
    'Gold Coin',
    'Commemorative Coin',
    'Currency Set',
    'Coin Album',
    'Rare Coin',
    'Bullion Coin',
    'Proof Set',
    'Coin Display',
    'Currency Collection',
  ],
  stamps: [
    'Postage Stamps',
    'Stamp Album',
    'Stamp Hinges',
    'Stamp Tongs',
    'Magnifying Glass',
    'Stamp Catalog',
    'First Day Cover',
    'Stamp Mounts',
    'Stamp Storage',
    'Stamp Collection',
  ],
  'sports-memorabilia': [
    'Autographed Baseball',
    'Sports Card',
    'Team Jersey',
    'Championship Ring',
    'Trophy',
    'Sports Poster',
    'Game Ball',
    'Team Photo',
    'Sports Equipment',
    'Championship Banner',
  ],
  'trading-cards': [
    'Baseball Cards',
    'Pokemon Cards',
    'Magic Cards',
    'Football Cards',
    'Basketball Cards',
    'Card Sleeves',
    'Card Binder',
    'Card Box',
    'Card Sleeves',
    'Trading Card Game',
  ],
  'collectible-action-figures': [
    'Limited Edition Figure',
    'Collectible Statue',
    'Action Figure Set',
    'Vintage Figure',
    'Exclusive Figure',
    'Figure Display Case',
    'Collectible Bust',
    'Figure Stand',
    'Collectible Set',
    'Rare Figure',
  ],
  'art-prints': [
    'Art Print',
    'Limited Edition Print',
    'Vintage Poster',
    'Artwork Reproduction',
    'Gallery Print',
    'Artist Print',
    'Signed Print',
    'Art Poster',
    'Fine Art Print',
    'Collectible Art',
  ],
  'vintage-items': [
    'Vintage Clothing',
    'Retro Electronics',
    'Vintage Toys',
    'Classic Car Parts',
    'Vintage Books',
    'Retro Furniture',
    'Vintage Cameras',
    'Classic Records',
    'Vintage Jewelry',
    'Retro Decor',
  ],
  'limited-editions': [
    'Limited Edition Book',
    'Exclusive Collectible',
    'Special Edition Item',
    "Collector's Item",
    'Rare Edition',
    'Limited Release',
    'Exclusive Figure',
    'Special Edition Set',
    "Collector's Edition",
    'Limited Run',
  ],
  'display-storage': [
    'Display Case',
    'Collectible Cabinet',
    'Display Stand',
    'Storage Box',
    'Protective Case',
    'Display Rack',
    'Collectible Shelf',
    'Display Frame',
    'Storage Container',
    'Protective Sleeve',
  ],

  // Digital Services
  software: [
    'Photo Editing Software',
    'Video Editing Software',
    'Office Suite',
    'Antivirus Software',
    'Design Software',
    'Accounting Software',
    'Project Management Tool',
    'Database Software',
    'Development Tool',
    'Graphics Software',
  ],
  'digital-media': [
    'E-book',
    'Digital Music Album',
    'Online Course',
    'Digital Artwork',
    'Software License',
    'Digital Magazine',
    'Online Training',
    'Digital Template',
    'Virtual Event',
    'Digital Asset',
  ],
  'online-courses': [
    'Programming Course',
    'Design Course',
    'Business Course',
    'Language Course',
    'Photography Course',
    'Marketing Course',
    'Writing Course',
    'Music Course',
    'Art Course',
    'Cooking Course',
  ],
  'web-services': [
    'Web Hosting',
    'Domain Registration',
    'SSL Certificate',
    'Website Builder',
    'Cloud Storage',
    'Email Service',
    'CDN Service',
    'Backup Service',
    'Monitoring Service',
    'Analytics Service',
  ],
  'mobile-apps': [
    'Mobile Game',
    'Productivity App',
    'Fitness App',
    'Photo App',
    'Music App',
    'Travel App',
    'Shopping App',
    'News App',
    'Social App',
    'Utility App',
  ],
  'cloud-services': [
    'Cloud Computing',
    'Data Storage',
    'Backup Service',
    'Cloud Database',
    'Server Hosting',
    'Cloud Security',
    'API Service',
    'Cloud Analytics',
    'Cloud Migration',
    'Cloud Monitoring',
  ],
  'digital-marketing': [
    'SEO Service',
    'Social Media Marketing',
    'Email Marketing',
    'Content Marketing',
    'PPC Advertising',
    'Influencer Marketing',
    'Marketing Analytics',
    'Brand Strategy',
    'Digital Advertising',
    'Marketing Automation',
  ],
  'design-services': [
    'Logo Design',
    'Web Design',
    'Graphic Design',
    'UI/UX Design',
    'Brand Design',
    'Print Design',
    'Packaging Design',
    'Illustration',
    'Photography',
    'Video Production',
  ],
  'digital-consulting': [
    'IT Consulting',
    'Digital Strategy',
    'Technology Consulting',
    'Business Consulting',
    'Digital Transformation',
    'Process Optimization',
    'System Integration',
    'Digital Innovation',
    'Change Management',
    'Digital Advisory',
  ],
  'support-services': [
    'Technical Support',
    'Customer Service',
    'Help Desk',
    'IT Support',
    'Maintenance Service',
    'Troubleshooting',
    'System Administration',
    'Network Support',
    'Software Support',
    'Hardware Support',
  ],
};

// Generate product data for each subcategory
function generateProductsForSubcategory(
  subcategorySlug: string,
  categoryName: string,
  subcategoryName: string
): ProductData[] {
  const products: ProductData[] = [];
  const productNameList = productNames[subcategorySlug] || [];

  for (let i = 1; i <= 10; i++) {
    const basePrice = Math.floor(Math.random() * 500) + 10; // Random price between $10-$510
    const hasSalePrice = Math.random() > 0.7; // 30% chance of having a sale price
    const salePrice = hasSalePrice ? Math.floor(basePrice * 0.8) : undefined; // 20% discount

    // Use realistic product name if available, otherwise generate one
    const productName = productNameList[i - 1] || `${subcategoryName} ${i}`;

    products.push({
      name: productName,
      description: `High-quality ${productName.toLowerCase()} in the ${categoryName.toLowerCase()} category. This product offers excellent value and performance with premium materials and craftsmanship.`,
      sku: `${subcategorySlug.toUpperCase()}-${i.toString().padStart(3, '0')}`,
      isFeatured: Math.random() > 0.8, // 20% chance of being featured
      sortOrder: i,
      subcategorySlug,
      prices: [
        {
          price: basePrice,
          salePrice,
          currency: 'USD',
        },
      ],
      stock: {
        quantity: Math.floor(Math.random() * 100) + 1, // Random stock between 1-100
        reserved: 0,
        minThreshold: 5,
        maxThreshold: 200,
      },
    });
  }

  return products;
}

export async function seedProducts(): Promise<void> {
  console.log('📦 Seeding products...');

  const subcategories = await getSubcategories();

  let seededCount = 0;
  let priceCount = 0;

  for (const subcategory of subcategories) {
    const products = generateProductsForSubcategory(
      subcategory.slug,
      subcategory.category.name,
      subcategory.name
    );

    for (const productData of products) {
      // Create the product
      const product = await prisma.product.upsert({
        where: { sku: productData.sku },
        update: {
          name: productData.name,
          description: productData.description,
          isFeatured: productData.isFeatured,
          sortOrder: productData.sortOrder,
          categoryId: subcategory.categoryId,
          subcategoryId: subcategory.id,
        },
        create: {
          name: productData.name,
          description: productData.description,
          sku: productData.sku,
          isFeatured: productData.isFeatured,
          sortOrder: productData.sortOrder,
          categoryId: subcategory.categoryId,
          subcategoryId: subcategory.id,
        },
      });

      // Create prices for the product
      for (const priceData of productData.prices) {
        await prisma.price.create({
          data: {
            productId: product.id,
            price: priceData.price,
            salePrice: priceData.salePrice,
            currency: priceData.currency,
          },
        });
        priceCount++;
      }

      // Create stock for the product
      await prisma.stock.create({
        data: {
          productId: product.id,
          quantity: productData.stock.quantity,
          reserved: productData.stock.reserved,
          minThreshold: productData.stock.minThreshold,
          maxThreshold: productData.stock.maxThreshold,
          isInStock: true,
        },
      });

      seededCount++;
    }
  }

  console.log(`✅ Seeded ${seededCount} products with ${priceCount} prices`);
}

export async function getProducts() {
  return await prisma.product.findMany({
    include: {
      category: true,
      subcategory: true,
      prices: true,
    },
  });
}
